PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {
  ?s skos:exactMatch ?nuts .
} WHERE {
  VALUES ?nisScheme {
    <http://vocab.belgif.be/auth/refnis2019>
    <http://vocab.belgif.be/auth/refnis2025>
  }

  ?s a prov:Location;
    skos:exactMatch ?nis .

  ?nis skos:inScheme ?nisScheme ;
    skos:exactMatch ?nuts .
}
