PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX schema: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
  ?s ?p ?o.
} WHERE {
  ?s a prov:Location;
    ?p ?o.

  FILTER (?p IN (
    rdf:type,
    mu:uuid,
    schema:label,
    ext:werkingsgebiedNiveau
  ))
}
