DELETE {
  GRAPH ?bestuurseenheidGraph {
    ?instance <http://www.w3.org/ns/adms#status> ?oldStatus .
  }
} INSERT {
  GRAPH ?bestuurseenheidGraph {
    ?instance <http://www.w3.org/ns/adms#status> <http://lblod.data.gift/concepts/instance-status/ontwerp> .
  }
} WHERE {
  VALUES ?instance {
    <http://data.lblod.info/id/public-service/78e91ed3-ffb0-4ea7-9642-5aa219d35957>
    <http://data.lblod.info/id/public-service/07fe200e-a7aa-4ff1-b8ff-feefbe9c78bd>
    <http://data.lblod.info/id/public-service/a0bd058d-d4f0-4c34-b470-3780ed3bdd0f>
  }

  GRAPH ?bestuurseenheidGraph {
    ?instance <http://www.w3.org/ns/adms#status> ?oldStatus .
  }

  FILTER(
    STRSTARTS(STR(?bestuurseenheidGraph), "http://mu.semte.ch/graphs/organizations/") &&
    STRENDS(STR(?bestuurseenheidGraph), "/LoketLB-LPDCGebruiker")
  )
}
