PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?pzRivierenland skos:prefLabel ?oldLabel .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?pzRivierenland skos:prefLabel "PZ Bornem/Puurs-Sint-Amands/Mechelen/Willebroek" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?pzRivierenland skos:prefLabel ?oldLabel .
    VALUES ?pzRivierenland {
      <http://data.lblod.info/id/bestuurseenheden/81dd243d-f66c-4157-b105-5407aa83cb62>
    }
  }
}
