PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a skos:Concept.
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s skos:inScheme <https://productencatalogus.data.vlaanderen.be/id/conceptscheme/IPDCOrganisaties>.
    FILTER NOT EXISTS { ?s a skos:Concept. }
  }
}
