PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX lpdcExt: <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#>
PREFIX schema: <http://schema.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/c648ea5d12626ee3364a02debb223908a71e68f53d69a7a7136585b58a083e77> {
    <http://data.lblod.info/id/persoon/a7c3e9f2b8d14056e3a1c7f0d2b89e45>
      a foaf:Person ;
      foaf:member <http://data.lblod.info/id/bestuurseenheden/c648ea5d12626ee3364a02debb223908a71e68f53d69a7a7136585b58a083e77> ;
      foaf:firstName "Test" ;
      foaf:familyName "User" ;
      lpdcExt:hasNotificationPreference <http://data.lblod.info/id/notification-preferences/f1e2d3c4-b5a6-7890-cdef-012345678901> .
  }

  GRAPH <http://mu.semte.ch/graphs/organizations/c648ea5d12626ee3364a02debb223908a71e68f53d69a7a7136585b58a083e77/LoketLB-LPDCGebruiker> {

    <http://data.lblod.info/id/notification-preferences/f1e2d3c4-b5a6-7890-cdef-012345678901>
      a lpdcExt:NotificationPreference ;
      mu:uuid "f1e2d3c4-b5a6-7890-cdef-012345678901" ;
      schema:email "test@example.com" ;
      lpdcExt:hasNotificationRuleConfig <http://data.lblod.info/id/notification-rule-configs/c3d4e5f6-a7b8-9012-cdef-123456789012> ;
      lpdcExt:hasNotificationRuleConfig <http://data.lblod.info/id/notification-rule-configs/1b58b0f3-582d-43f2-a6e5-8da247223f58> ;
      lpdcExt:hasNotificationRuleConfig <http://data.lblod.info/id/notification-rule-configs/43768631-fdde-4a41-934c-9936d73b0bd9> ;
      lpdcExt:notificationInstance <http://data.lblod.info/id/public-service/2bc7d6b7-d134-459d-9a66-7dea329170ca> ;
      lpdcExt:notificationInstance <http://data.lblod.info/id/public-service/de97836e-8a72-456e-912b-42ff79008b4c> ;
      lpdcExt:notificationInstance <http://data.lblod.info/id/public-service/1babf63a-a053-4c61-b1b8-adfe00c84c96> ;
      lpdcExt:notificationInstance <http://data.lblod.info/id/public-service/34f631e8-d7fc-4c89-9c0c-901db34cf18a> .

    <http://data.lblod.info/id/notification-rule-configs/c3d4e5f6-a7b8-9012-cdef-123456789012>
      a lpdcExt:NotificationRuleConfig ;
      mu:uuid "c3d4e5f6-a7b8-9012-cdef-123456789012" ;
      lpdcExt:notificationFrequency "weekly" ;
      lpdcExt:hasEnabledRule <http://lblod.data.gift/concepts/60cd1b30-fa29-4fd9-a618-2f8566153849> .

    <http://data.lblod.info/id/notification-rule-configs/1b58b0f3-582d-43f2-a6e5-8da247223f58>
      a lpdcExt:NotificationRuleConfig ;
      mu:uuid "1b58b0f3-582d-43f2-a6e5-8da247223f58" ;
      lpdcExt:notificationFrequency "weekly" ;
      lpdcExt:hasEnabledRule <http://lblod.data.gift/concepts/83d7bade-9b45-4d28-9348-3edcdcf99edc> .

    <http://data.lblod.info/id/notification-rule-configs/43768631-fdde-4a41-934c-9936d73b0bd9>
      a lpdcExt:NotificationRuleConfig ;
      mu:uuid "43768631-fdde-4a41-934c-9936d73b0bd9" ;
      lpdcExt:notificationFrequency "weekly" ;
      lpdcExt:hasEnabledRule <http://lblod.data.gift/concepts/906311f3-f9f0-4b02-80de-d339df39a4ad> .
  }
}