PREFIX dvc: <https://productencatalogus.data.vlaanderen.be/id/concept/YourEuropeCategorie/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

DELETE {
  GRAPH ?g {
    ?subject <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#yourEuropeCategory> ?concept ;
             a <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#InstancePublicService> .
  }
}
WHERE {
  GRAPH ?g {
    VALUES ?concept {
      dvc:Reizen
      dvc:WerkEnPensionering
      dvc:Voertuigen
      dvc:Verblijf
      dvc:OnderwijsOfStage
      dvc:Gezondheidszorg
      dvc:BurgerEnFamilieRechten
      dvc:Consumentenrechten
      dvc:BeschermingPersoonsgegevens
      dvc:Bedrijf
      dvc:Werknemers
      dvc:Belastingen
      dvc:Goederen
      dvc:Diensten
      dvc:Bedrijfsfinanciering
      dvc:Overheidsopdrachten
      dvc:GezondheidVeiligheidWerk
      dvc:ProcedureGeboorte
      dvc:ProcedureVerblijf
      dvc:ProcedureStudie
      dvc:ProcedureWerk
      dvc:ProcedureVerhuizing
      dvc:ProcedurePensionering
      dvc:ProcedureStartenExploiterenSluitenBedrijf
    }
    ?subject <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#yourEuropeCategory> ?concept .
  }
}
