services:
  ######################
  # START: CONTROLE
  ######################
  controle:
    image: lblod/frontend-lpdc:<the correct version here>
    environment:
      VIRTUAL_HOST: "acc.controle.lpdc.lpdc-dev.s.redhost.be"
      LETSENCRYPT_HOST: "acc.controle.lpdc.lpdc-dev.s.redhost.be"
      LETSENCRYPT_EMAIL: "info@redpencil.io"
      EMBER_LOKET_URL: "https://controle.loket.lblod.info/"
    volumes:
      - ./config/basic-auth:/etc/nginx/conf.d
    links:
      - controle-identifier:backend
    networks:
      - proxy
      - default
    restart: always
    labels:
      - "logging=true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  controle-identifier:
    image: semtech/mu-identifier:1.10.0
    environment:
      LOG_OUTGOING_ALLOWED_GROUPS: "true"
      LOG_ALLOWED_GROUPS: "true"
      LOG_INCOMING_ALLOWED_GROUPS: "true"
      LOG_SESSION_ID: "true"
    labels:
      - "logging=true"
    links:
      - controle-dispatcher:dispatcher
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  controle-dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    volumes:
      - ./config/controle-dispatcher:/config
    labels:
      - "logging=true"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

######################
# END: CONTROLE
######################
  identifier:
    environment:
      VIRTUAL_HOST: "dashboard.acc.lpdc.lokaalbestuur.lblod.info"
      LETSENCRYPT_HOST: "dashboard.acc.lpdc.lokaalbestuur.lblod.info"
      LETSENCRYPT_EMAIL: "info@redpencil.io"

  lpdc:
    environment:
      VIRTUAL_HOST: "acc.lpdc-dev.s.redhost.be,acc.lpdc.lokaalbestuur.lblod.info"
      LETSENCRYPT_HOST: "acc.lpdc-dev.s.redhost.be,acc.lpdc.lokaalbestuur.lblod.info"
      LETSENCRYPT_EMAIL: "info@redpencil.io"
      EMBER_LOKET_URL: "https://loket.lblod.info/"
      EMBER_IPDC_URL: "https://productcatalogus.ipdc.vlaanderen.be"
      EMBER_ACMIDM_CLIENT_ID: "<ACMIDM_CLIENT_ID>"
      EMBER_ACMIDM_AUTH_URL: "https://authenticatie.vlaanderen.be/op/v1/auth"
      EMBER_ACMIDM_LOGOUT_URL: "https://authenticatie.vlaanderen.be/op/v1/logout"
      EMBER_ACMIDM_AUTH_REDIRECT_URL: "https://acc.lpdc.lokaalbestuur.lblod.info/authorization/callback"
      EMBER_ACMIDM_SWITCH_REDIRECT_URL: "https://acc.lpdc.lokaalbestuur.lblod.info/switch-login"
    networks:
      - proxy
      - default

  login:
    environment:
      MU_APPLICATION_AUTH_DISCOVERY_URL: "https://authenticatie.vlaanderen.be/op"
      MU_APPLICATION_AUTH_CLIENT_ID: "<ACMIDM_CLIENT_ID>"
      MU_APPLICATION_AUTH_REDIRECT_URI: "https://acc.lpdc.lokaalbestuur.lblod.info/authorization/callback"
      MU_APPLICATION_AUTH_CLIENT_SECRET: "<ACMIDM_AUTH_CLIENT_SECRET>"

  lpdc-publish:
    entrypoint: ["echo", "Service-disabled since production data cannot be connected to test ipdc environment"]
    restart: "no"

  ldes-consumer-conceptsnapshot-ipdc:
    entrypoint: ["echo", "Service-disabled since production data cannot be connected to test ipdc environment"]
    restart: "no"

networks:
  proxy:
    external:
      name: letsencrypt_default
