version: "3.7"

services:

  resource:
    image: semtech/mu-cl-resources:feature-supply-info-on-empty-included-arm64-build

  database:
    image: semtech/mu-authorization:feature-service-roam-r1.1-arm64-build

  cache:
    image: semtech/mu-cache:2.0.2-arm64-build

  migrations:
    image: semtech/mu-migrations-service:0.8.0-arm64-build

  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2-arm64-build

  identifier:
    image: semtech/mu-identifier:1.10.0-arm64-build

  deltanotifier:
    image: cecemel/delta-notifier:0.2.0-beta.3-arm64-build

  mocklogin:
    image: lblod/mock-login-service:0.4.0-arm64-build

  ldes-consumer-conceptsnapshot-ipdc:
    image: redpencil/ldes-consumer:feature-stability-improvements-r1.1-arm64-build

  file:
    image: cecemel/file-service:3.3.0-arm64-build

  report-generation:
    image: lblod/loket-report-generation-service:0.6.3-arm64-build

  lpdc-management:
    environment:
      ADRESSEN_REGISTER_API_KEY: <ADRESSEN_REGISTER_API_KEY>

  ipdc-ldes-consumer:
    image: redpencil/ldes-consumer:feature-stability-improvements-r1.1-arm64-build

  ldes-consumer-instancesnapshot-example:
    image: redpencil/ldes-consumer:feature-stability-improvements-r1.1-arm64-build