DELETE {
    GRAPH ?bestuurseenheidGraph {
        ?instance <http://schema.org/publication> <http://lblod.data.gift/concepts/a7d01120-6f93-11ed-bcb8-a144c50c46d7> .
    }
}
INSERT {
    GRAPH ?bestuurseenheidGraph {
        ?instance <http://schema.org/publication> <http://lblod.data.gift/concepts/publication-status/te-herpubliceren> .
    }
}
WHERE {
    GRAPH ?bestuurseenheidGraph {
        ?instance a <https://www.w3.org/ns/activitystreams#Tombstone> .
        ?instance <http://schema.org/publication> <http://lblod.data.gift/concepts/a7d01120-6f93-11ed-bcb8-a144c50c46d7> .
    }

    FILTER(
    STRSTARTS(STR(?bestuurseenheidGraph), "http://mu.semte.ch/graphs/organizations/") &&
    STRENDS(STR(?bestuurseenheidGraph), "/LoketLB-LPDCGebruiker")
    )
}

