DELETE {
    GRAPH ?bestuurseenheidGraph {
        ?address <https://data.vlaanderen.be/ns/adres#land> ?existingBelgiumOrSomethingElse .
    }
}
INSERT {
    GRAPH ?bestuurseenheidGraph {
        ?address <https://data.vlaanderen.be/ns/adres#land> "België"@nl .
    }
}
WHERE {
    GRAPH ?bestuurseenheidGraph {
        ?instance a <http://purl.org/vocab/cpsv#PublicService> .
        ?instance <http://data.europa.eu/m8g/hasContactPoint> ?contactPoint .
        ?contactPoint <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#address> ?address .
        ?address <https://data.vlaanderen.be/ns/adres#land> ?existingBelgiumOrSomethingElse .
    }

    FILTER(
    STRSTARTS(STR(?bestuurseenheidGraph), "http://mu.semte.ch/graphs/organizations/") &&
    STRENDS(STR(?bestuurseenheidGraph), "/LoketLB-LPDCGebruiker")
    )
}

