DELETE DATA FROM <http://mu.semte.ch/graphs/organizations/842737db3afe0bad6a72bbbdeee376fe49abe721975d549d81bb22c70bc7002d/LoketLB-LPDCGebruiker> {
<http://data.lblod.info/id/public-service/6619d4e9-b593-4572-916f-d9c8ea6a832e> <http://purl.org/dc/terms/description>"<p>You can receive a subsidy if you start an independent nursery and create childcare places in preschool childcare (0\u20133 years).<br><br>\u200BThe subsidy shall be granted to:\r<br><ul><li>Independent nurseries with a certificate of supervision (issued by Child and Family). </li><li>Nurseries recognized and subsidized by Child and Family. </li><li>Cooperating childminders who take care of 9 or more children, on an independent basis with a certificate of supervision or affiliated with a recognized service for childminders. </li><li>Initiatives for out-of-school childcare with an agreement in principle (awarded by Child and Family) or recognition. </li></ul></p>"@en .
}


