DELETE {
    GRAPH <http://mu.semte.ch/graphs/lpdc/ipdc-publication-errors> {
        ?s ?p ?o.
    }
} WHERE {
    GRAPH <http://mu.semte.ch/graphs/lpdc/ipdc-publication-errors> {
        ?s ?p ?o.
    }
}