DELETE DATA FROM <http://mu.semte.ch/graphs/organizations/3eb8c9fae32d02359dcd7b22e2a74e67a5b48388df31ad819c27c688fedd10b0/LoketLB-LPDCGebruiker>{
<http://data.lblod.info/id/public-service/e5b462d0-40c0-4b33-8281-7afa15d0c5be> <http://data.europa.eu/m8g/hasCompetentAuthority> <https://data.vlaanderen.be/id/organisatie/OVO001708> .
<http://data.lblod.info/id/public-service/e5b462d0-40c0-4b33-8281-7afa15d0c5be> <http://data.europa.eu/m8g/thematicArea> <https://productencatalogus.data.vlaanderen.be/id/concept/Thema/WelzijnGezondheid> .
<http://data.lblod.info/id/public-service/e5b462d0-40c0-4b33-8281-7afa15d0c5be> <http://purl.org/dc/terms/spatial> <http://vocab.belgif.be/auth/refnis2019/23032> .
<http://data.lblod.info/id/public-service/e5b462d0-40c0-4b33-8281-7afa15d0c5be> <http://purl.org/dc/terms/type> <https://productencatalogus.data.vlaanderen.be/id/concept/Type/Toelating> .
<http://data.lblod.info/id/public-service/e5b462d0-40c0-4b33-8281-7afa15d0c5be> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.org/vocab/cpsv#PublicService> .
<http://data.lblod.info/id/public-service/e5b462d0-40c0-4b33-8281-7afa15d0c5be> <http://www.w3.org/ns/dcat#keyword> "crematie"@en .
<http://data.lblod.info/id/public-service/e5b462d0-40c0-4b33-8281-7afa15d0c5be> <http://www.w3.org/ns/dcat#keyword> "cremeren"@en .
<http://data.lblod.info/id/public-service/e5b462d0-40c0-4b33-8281-7afa15d0c5be> <http://www.w3.org/ns/dcat#keyword> "cremeren"@nl .
<http://data.lblod.info/id/public-service/e5b462d0-40c0-4b33-8281-7afa15d0c5be> <http://www.w3.org/ns/dcat#keyword> "toelating"@en .
<http://data.lblod.info/id/public-service/e5b462d0-40c0-4b33-8281-7afa15d0c5be> <http://www.w3.org/ns/dcat#keyword> "toelating"@nl .
<http://data.lblod.info/id/public-service/e5b462d0-40c0-4b33-8281-7afa15d0c5be> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#competentAuthorityLevel> <https://productencatalogus.data.vlaanderen.be/id/concept/BevoegdBestuursniveau/Vlaams> .
<http://data.lblod.info/id/public-service/e5b462d0-40c0-4b33-8281-7afa15d0c5be> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#conceptTag> <https://productencatalogus.data.vlaanderen.be/id/concept/ConceptTag/YourEuropeVerplicht> .
<http://data.lblod.info/id/public-service/e5b462d0-40c0-4b33-8281-7afa15d0c5be> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#executingAuthorityLevel> <https://productencatalogus.data.vlaanderen.be/id/concept/UitvoerendBestuursniveau/Lokaal> .
<http://data.lblod.info/id/public-service/e5b462d0-40c0-4b33-8281-7afa15d0c5be> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#hasExecutingAuthority> <http://data.lblod.info/id/bestuurseenheden/3eb8c9fae32d02359dcd7b22e2a74e67a5b48388df31ad819c27c688fedd10b0> .
<http://data.lblod.info/id/public-service/e5b462d0-40c0-4b33-8281-7afa15d0c5be> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#publicationMedium> <https://productencatalogus.data.vlaanderen.be/id/concept/PublicatieKanaal/YourEurope> .
<http://data.lblod.info/id/public-service/e5b462d0-40c0-4b33-8281-7afa15d0c5be> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#targetAudience> <https://productencatalogus.data.vlaanderen.be/id/concept/Doelgroep/Burger> .
<http://data.lblod.info/id/public-service/e5b462d0-40c0-4b33-8281-7afa15d0c5be> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#yourEuropeCategory> <https://productencatalogus.data.vlaanderen.be/id/concept/YourEuropeCategorie/VerblijfOverlijden> .
}