DELETE {
    GRAPH ?bestuurseenheidGraph {
        ?instance <http://www.w3.org/ns/adms#status> <http://lblod.data.gift/concepts/79a52da4-f491-4e2f-9374-89a13cde8ecd> .
    }
}
INSERT {
    GRAPH ?bestuurseenheidGraph {
        ?instance <http://www.w3.org/ns/adms#status> <http://lblod.data.gift/concepts/instance-status/ontwerp> .
    }
}
WHERE {
    GRAPH ?bestuurseenheidGraph {
        ?instance a <http://purl.org/vocab/cpsv#PublicService> .
        ?instance <http://www.w3.org/ns/adms#status> <http://lblod.data.gift/concepts/79a52da4-f491-4e2f-9374-89a13cde8ecd> .
    }

    FILTER(
    STRSTARTS(STR(?bestuurseenheidGraph), "http://mu.semte.ch/graphs/organizations/") &&
    STRENDS(STR(?bestuurseenheidGraph), "/LoketLB-LPDCGebruiker")
    )
}