DELETE {
    GRAPH <http://mu.semte.ch/graphs/organizations/28346950e285b8b816133fece5ac9408097c3f190c7f32573cf0c640d6c34b1a/LoketLB-LPDCGebruiker> {
        <http://data.lblod.info/id/public-service/40dc93c4-d723-4f10-9198-d0a7baa0a25b> <http://purl.org/dc/terms/description> ?description
    }
}WHERE {
    GRAPH <http://mu.semte.ch/graphs/organizations/28346950e285b8b816133fece5ac9408097c3f190c7f32573cf0c640d6c34b1a/LoketLB-LPDCGebruiker> {
        <http://data.lblod.info/id/public-service/40dc93c4-d723-4f10-9198-d0a7baa0a25b> <http://purl.org/dc/terms/description> ?description

    FILTER(CONTAINS(?description, "For large events, outdoors, where electronically amplified music is played (festival, gig, carnival, open-air event, dance party, special occasion) with a noise level higher than 85 dB(A)LAeq,15min and 92 dB(A)LAmax,slow, you must apply for a deviation from the noise standards with the college of mayor and aldermen. <br>Request your deviation using the online form: https://www.brugge.be/muziek-afwijking-aanvragen"))
    }
};


DELETE {
   GRAPH <http://mu.semte.ch/graphs/organizations/71e6c6f58d20f6db457245a70394f2d63f601a32f8ccbc7e443e98f8d06b0b0e/LoketLB-LPDCGebruiker>{
        <http://data.lblod.info/id/public-service/7ab54e89-41c4-4acd-b08d-44eb6a207d1d> <http://purl.org/dc/terms/description> ?description
    }
}WHERE {
    GRAPH <http://mu.semte.ch/graphs/organizations/71e6c6f58d20f6db457245a70394f2d63f601a32f8ccbc7e443e98f8d06b0b0e/LoketLB-LPDCGebruiker> {
        <http://data.lblod.info/id/public-service/7ab54e89-41c4-4acd-b08d-44eb6a207d1d> <http://purl.org/dc/terms/description> ?description

    FILTER(CONTAINS(?description, "The city shall levy a tax on displays, events and entertainments on the territory of the city with an exceptionally concentrated audience attendance within a short period of time. In order to be exceptional event, at least 10,000 paying visitors recorded per organization. Organizations spread over several days are considered one organization."))
    }
};

DELETE {
   GRAPH <http://mu.semte.ch/graphs/organizations/08e1b1e460bc9a9dfbd6570ab96a6b4813fbd4d9df2294dad86b11d9e4093d32/LoketLB-LPDCGebruiker>{
        <http://data.lblod.info/id/public-service/c9aa66c0-6373-46c7-8283-9ff5a0fdde03> <http://purl.org/dc/terms/description> ?description
    }
}WHERE {
    GRAPH <http://mu.semte.ch/graphs/organizations/08e1b1e460bc9a9dfbd6570ab96a6b4813fbd4d9df2294dad86b11d9e4093d32/LoketLB-LPDCGebruiker> {
        <http://data.lblod.info/id/public-service/c9aa66c0-6373-46c7-8283-9ff5a0fdde03> <http://purl.org/dc/terms/description> ?description

    FILTER(CONTAINS(?description, "<p>Marriage is a union between two people officiated by a registrar. The marriage takes place at the town hall, but can also take place in another public place of neutral character, if the local council has designated such a place.<br><br>​You can marry:<br></p><ul><li>on all weekdays between 9 and 11:30 a.m. and between 2 and 5 p.m. (between 5 and 6 p.m. subject to fee)</li><li>on Saturday in the morning (subject to remuneration)</li><li>you cannot get married in Langemark-Poelkapelle on Sundays and holidays.</li></ul><p></p>"))
    }
};

DELETE DATA FROM <http://mu.semte.ch/graphs/organizations/644341a5338a39472f7d096f3c1619ca0e8325a560f681f58896fa843cb17d2c/LoketLB-LPDCGebruiker>{
<http://data.lblod.info/id/public-service/659de301-969f-4677-8065-c49cede3defb> <http://purl.org/dc/terms/description> "* If you want to operate one of the following commercial businesses in Mortsel, you must apply for an operating permit:\r<br>- massage parlour;\r<br>- shisha bar;\r<br>- CBD shop;\r<br>- sex establishment;\r<br>- night shop;\r<br>- private telecommunications agency;\r<br>- club-vzw."@en .

<http://data.lblod.info/id/public-service/659de301-969f-4677-8065-c49cede3defb> <http://purl.org/dc/terms/description> "If you want to operate one of the following commercial businesses in Mortsel, you must apply for an operating permit:<br>- massage parlour;<br>- shisha bar;<br>- CBD shop;<br>- sex establishment;<br>- night shop;<br>- private telecommunications agency;<br>- club-vzw."@en .
};



