DELETE {
    GRAPH ?bestuurseenheidGraph {
        ?instance <http://www.w3.org/ns/adms#status> <http://lblod.data.gift/concepts/instance-status/verstuurd>.
    }
}
INSERT {
    GRAPH ?bestuurseenheidGraph {
        ?instance <http://www.w3.org/ns/adms#status> <http://lblod.data.gift/concepts/instance-status/verzonden>.
    }
}
WHERE {
    GRAPH ?bestuurseenheidGraph {
        ?instance a <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#InstancePublicService> .
        ?instance <http://www.w3.org/ns/adms#status> <http://lblod.data.gift/concepts/instance-status/verstuurd>.
    }
    FILTER(
    STRSTARTS(STR(?bestuurseenheidGraph), "http://mu.semte.ch/graphs/organizations/") &&
    STRENDS(STR(?bestuurseenheidGraph), "/LoketLB-LPDCGebruiker"))
}