DELETE {
    GRAPH ?bestuurseenheidGraph {
        ?instance <http://schema.org/productID> ?o.
    }
}
WHERE {
    GRAPH ?bestuurseenheidGraph {
        ?instance a <http://purl.org/vocab/cpsv#PublicService> .
        ?instance <http://schema.org/productID> ?o .
    }

    FILTER(
    STRSTARTS(STR(?bestuurseenheidGraph), "http://mu.semte.ch/graphs/organizations/") &&
    STRENDS(STR(?bestuurseenheidGraph), "/LoketLB-LPDCGebruiker")
    )
}