DELETE DATA FROM <http://mu.semte.ch/graphs/organizations/6463c55877def582f642cb5b3b4a7eab60d8d8dd9779fc45d87e4c8aa5d9a07e/LoketLB-LPDCGebruiker>{
<http://data.lblod.info/id/cost/370748ca-3934-4252-ab3c-2069defa3e03> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://data.europa.eu/m8g/Cost> .
<http://data.lblod.info/id/cost/370748ca-3934-4252-ab3c-2069defa3e03> <http://www.w3.org/ns/shacl#order> "1"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://data.lblod.info/id/public-service/d43ac76a-8aad-4979-8c55-d06c3871abff> <http://data.europa.eu/m8g/hasCompetentAuthority> <https://data.vlaanderen.be/id/organisatie/OVO000096> .
<http://data.lblod.info/id/public-service/d43ac76a-8aad-4979-8c55-d06c3871abff> <http://data.europa.eu/m8g/hasCost> <http://data.lblod.info/id/cost/370748ca-3934-4252-ab3c-2069defa3e03> .
<http://data.lblod.info/id/public-service/d43ac76a-8aad-4979-8c55-d06c3871abff> <http://data.europa.eu/m8g/thematicArea> <https://productencatalogus.data.vlaanderen.be/id/concept/Thema/MobiliteitOpenbareWerken> .
<http://data.lblod.info/id/public-service/d43ac76a-8aad-4979-8c55-d06c3871abff> <http://mu.semte.ch/vocabularies/core/uuid> "f3b08f58-591c-47e2-8e3f-9078c60ae7c3" .
<http://data.lblod.info/id/public-service/d43ac76a-8aad-4979-8c55-d06c3871abff> <http://purl.org/dc/terms/description> "<p>As of 1 July 2020, taxi drivers, both licence holders who are themselves drivers as well as their personnel, must be in possession of a driver’s pass.</p>"@en .
<http://data.lblod.info/id/public-service/d43ac76a-8aad-4979-8c55-d06c3871abff> <http://purl.org/dc/terms/description> "<p>Taxibestuurders, zowel vergunninghouders die zelf rijden als hun personeelsleden, moeten sinds 1 juli 2020 in het bezit zijn van een bestuurderspas.</p>"@nl .
<http://data.lblod.info/id/public-service/d43ac76a-8aad-4979-8c55-d06c3871abff> <http://purl.org/dc/terms/source> <https://ipdc.vlaanderen.be/id/concept/4e7ddbd8-9b94-4985-b6ea-e267e2e3594e> .
<http://data.lblod.info/id/public-service/d43ac76a-8aad-4979-8c55-d06c3871abff> <http://purl.org/dc/terms/title> "Bestuurderspas voor taxibestuurders"@nl .
<http://data.lblod.info/id/public-service/d43ac76a-8aad-4979-8c55-d06c3871abff> <http://purl.org/dc/terms/title> "Driver’s pass for taxi drivers"@en .
<http://data.lblod.info/id/public-service/d43ac76a-8aad-4979-8c55-d06c3871abff> <http://purl.org/dc/terms/type> <https://productencatalogus.data.vlaanderen.be/id/concept/Type/FinancieleVerplichting> .
<http://data.lblod.info/id/public-service/d43ac76a-8aad-4979-8c55-d06c3871abff> <http://purl.org/vocab/cpsv#follows> <http://data.lblod.info/id/rule/48659e0f-b36b-43b5-ad70-55fc0b48e1ce> .
<http://data.lblod.info/id/public-service/d43ac76a-8aad-4979-8c55-d06c3871abff> <http://vocab.belgif.be/ns/publicservice#hasRequirement> <http://data.lblod.info/id/requirement/4d82392e-3154-4987-8e54-f3c7466006df> .
<http://data.lblod.info/id/public-service/d43ac76a-8aad-4979-8c55-d06c3871abff> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.org/vocab/cpsv#PublicService> .
<http://data.lblod.info/id/public-service/d43ac76a-8aad-4979-8c55-d06c3871abff> <http://www.w3.org/ns/dcat#keyword> "bestuurderpas"@en .
<http://data.lblod.info/id/public-service/d43ac76a-8aad-4979-8c55-d06c3871abff> <http://www.w3.org/ns/dcat#keyword> "bestuurderpas"@nl .
<http://data.lblod.info/id/public-service/d43ac76a-8aad-4979-8c55-d06c3871abff> <http://www.w3.org/ns/dcat#keyword> "taxi"@en .
<http://data.lblod.info/id/public-service/d43ac76a-8aad-4979-8c55-d06c3871abff> <http://www.w3.org/ns/dcat#keyword> "taxi"@nl .
<http://data.lblod.info/id/public-service/d43ac76a-8aad-4979-8c55-d06c3871abff> <http://www.w3.org/ns/dcat#keyword> "verplicht"@en .
<http://data.lblod.info/id/public-service/d43ac76a-8aad-4979-8c55-d06c3871abff> <http://www.w3.org/ns/dcat#keyword> "verplicht"@nl .
<http://data.lblod.info/id/public-service/d43ac76a-8aad-4979-8c55-d06c3871abff> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#competentAuthorityLevel> <https://productencatalogus.data.vlaanderen.be/id/concept/BevoegdBestuursniveau/Vlaams> .
<http://data.lblod.info/id/public-service/d43ac76a-8aad-4979-8c55-d06c3871abff> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#conceptTag> <https://productencatalogus.data.vlaanderen.be/id/concept/ConceptTag/YourEuropeVerplicht> .
<http://data.lblod.info/id/public-service/d43ac76a-8aad-4979-8c55-d06c3871abff> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#executingAuthorityLevel> <https://productencatalogus.data.vlaanderen.be/id/concept/UitvoerendBestuursniveau/Lokaal> .
<http://data.lblod.info/id/public-service/d43ac76a-8aad-4979-8c55-d06c3871abff> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#publicationMedium> <https://productencatalogus.data.vlaanderen.be/id/concept/PublicatieKanaal/YourEurope> .
<http://data.lblod.info/id/public-service/d43ac76a-8aad-4979-8c55-d06c3871abff> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#targetAudience> <https://productencatalogus.data.vlaanderen.be/id/concept/Doelgroep/Burger> .
<http://data.lblod.info/id/public-service/d43ac76a-8aad-4979-8c55-d06c3871abff> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#targetAudience> <https://productencatalogus.data.vlaanderen.be/id/concept/Doelgroep/Onderneming> .
<http://data.lblod.info/id/public-service/d43ac76a-8aad-4979-8c55-d06c3871abff> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#targetAudience> <https://productencatalogus.data.vlaanderen.be/id/concept/Doelgroep/Organisatie> .
<http://data.lblod.info/id/public-service/d43ac76a-8aad-4979-8c55-d06c3871abff> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#yourEuropeCategory> <https://productencatalogus.data.vlaanderen.be/id/concept/YourEuropeCategorie/DienstenLicentiesVergunningen> .
<http://data.lblod.info/id/requirement/4d82392e-3154-4987-8e54-f3c7466006df> <http://mu.semte.ch/vocabularies/core/uuid> "dfe201dd-8dab-4664-9e85-8035e37048dd" .
<http://data.lblod.info/id/requirement/4d82392e-3154-4987-8e54-f3c7466006df> <http://purl.org/dc/terms/description> "<p>In order to obtain a driver’s pass, you must</p>\n\n<ul>\n	<li>be at least <strong>21 years</strong> of age</li>\n	<li>have had a <strong>category B driving licence</strong> for at least two years (including a valid medical examination)</li>\n	<li>be able to produce an <strong>extract from the criminal records</strong> that is not older than three months</li>\n	<li>fulfil a<strong>ll statutory and regulatory conditions</strong> to exercise this professional activity in Belgium, and</li>\n	<li>be able to demonstrate a <strong>minimum knowledge of Dutch </strong>comparable to the Common European Framework of Reference for Languages <strong>level B1</strong>. Those who already hold a level A2 certificate have two years to achieve level B1.</li>\n</ul>"@en .
<http://data.lblod.info/id/requirement/4d82392e-3154-4987-8e54-f3c7466006df> <http://purl.org/dc/terms/description> "<p>Om een bestuurderspas te kunnen verkrijgen, moet u:</p>\n\n<ul>\n	<li>minstens <strong>21 jaar</strong> zijn;</li>\n	<li>minstens <strong>2 jaar</strong> over een <strong>rijbewijs categorie B</strong> beschikken, inclusief geldige medische keuring,</li>\n	<li>een <strong>uittreksel uit het strafregister</strong> kunnen voorleggen dat niet ouder is dan 3 maanden,</li>\n	<li>voldoen aan <strong>alle wettelijke en reglementaire voorwaarden</strong> om in België deze beroepsactiviteit uit te oefenen,</li>\n	<li>een bewijs van <strong>minimale kennis Nederlands op niveau B1</strong> van het Europees Referentiekader voor Talen. Wie over een bewijs van niveau A2 beschikt, krijgt 2 jaar de tijd om niveau B1 te halen.</li>\n</ul>"@nl .
<http://data.lblod.info/id/requirement/4d82392e-3154-4987-8e54-f3c7466006df> <http://purl.org/dc/terms/source> <http://mu.semte.ch/blank#7ba26ff6-f8a6-4bf7-b97b-4f14b2b32cf0> .
<http://data.lblod.info/id/requirement/4d82392e-3154-4987-8e54-f3c7466006df> <http://purl.org/dc/terms/title> "Requirements"@en .
<http://data.lblod.info/id/requirement/4d82392e-3154-4987-8e54-f3c7466006df> <http://purl.org/dc/terms/title> "Voorwaarden"@nl .
<http://data.lblod.info/id/requirement/4d82392e-3154-4987-8e54-f3c7466006df> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://data.europa.eu/m8g/Requirement> .
<http://data.lblod.info/id/requirement/4d82392e-3154-4987-8e54-f3c7466006df> <http://www.w3.org/ns/shacl#order> "1"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://data.lblod.info/id/rule/48659e0f-b36b-43b5-ad70-55fc0b48e1ce> <http://purl.org/dc/terms/description> "<p>Apply for the driver’s pass online</p>\n\n<ul>\n	<li>via the Centaurus2020 platform</li>\n	<li>or in the municipality or city in which you are domiciled.</li>\n</ul>"@en .
<http://data.lblod.info/id/rule/48659e0f-b36b-43b5-ad70-55fc0b48e1ce> <http://purl.org/dc/terms/description> "<p>U vraagt de bestuurderspas aan:</p>\n\n<ul>\n	<li><a data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"aa249554-84af-459f-89cc-644e6f5ca117\" href=\"https://centaurus2020.vlaanderen.be/\">online via het platform Centaurus 2020</a><br />\n	of</li>\n	<li>in de gemeente of stad waar u gedomicilieerd bent.</li>\n</ul>"@nl .
<http://data.lblod.info/id/rule/48659e0f-b36b-43b5-ad70-55fc0b48e1ce> <http://purl.org/dc/terms/title> "Procedure"@en .
<http://data.lblod.info/id/rule/48659e0f-b36b-43b5-ad70-55fc0b48e1ce> <http://purl.org/dc/terms/title> "Procedure"@nl .
<http://data.lblod.info/id/rule/48659e0f-b36b-43b5-ad70-55fc0b48e1ce> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.org/vocab/cpsv#Rule> .
<http://data.lblod.info/id/rule/48659e0f-b36b-43b5-ad70-55fc0b48e1ce> <http://www.w3.org/ns/shacl#order> "1"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://data.lblod.info/id/rule/48659e0f-b36b-43b5-ad70-55fc0b48e1ce> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#hasWebsite> <http://data.lblod.info/id/website/91cbd02c-08f0-4834-a977-c390c144721c> .
<http://data.lblod.info/id/website/91cbd02c-08f0-4834-a977-c390c144721c> <http://mu.semte.ch/vocabularies/core/uuid> "4f74a886-3962-4aaf-8c25-21a9201e8757" .
<http://data.lblod.info/id/website/91cbd02c-08f0-4834-a977-c390c144721c> <http://purl.org/dc/terms/source> <http://mu.semte.ch/blank#762ebfef-782d-45f0-9c57-bce212061115> .
<http://data.lblod.info/id/website/91cbd02c-08f0-4834-a977-c390c144721c> <http://purl.org/dc/terms/title> "Platform Centaurus 2020"@en .
<http://data.lblod.info/id/website/91cbd02c-08f0-4834-a977-c390c144721c> <http://purl.org/dc/terms/title> "Platform Centaurus 2020"@nl .
<http://data.lblod.info/id/website/91cbd02c-08f0-4834-a977-c390c144721c> <http://schema.org/url> "https://centaurus2020.vlaanderen.be" .
<http://data.lblod.info/id/website/91cbd02c-08f0-4834-a977-c390c144721c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/WebSite> .
<http://data.lblod.info/id/website/91cbd02c-08f0-4834-a977-c390c144721c> <http://www.w3.org/ns/shacl#order> "1"^^<http://www.w3.org/2001/XMLSchema#integer> .
}