DELETE {
    GRAPH ?g {
        ?s <http://purl.org/dc/terms/source> ?o.
    }
} WHERE {
    GRAPH ?g {
        VALUES ?type {
           <http://data.europa.eu/m8g/Requirement>
            <http://data.europa.eu/m8g/Evidence>
            <http://data.europa.eu/m8g/Cost>
            <http://purl.org/vocab/cpsv#Rule>
            <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#FinancialAdvantage>
            <http://schema.org/WebSite>
        }
        ?s a ?type.
        ?s <http://purl.org/dc/terms/source> ?o.
   }
}
