DELETE DATA FROM <http://mu.semte.ch/graphs/organizations/0efaaec80a4ad0328aebadee1ad36a787adff5e31490795ea411fb3644be7f60/LoketLB-LPDCGebruiker>{
<http://data.lblod.info/id/cost/6c9c0939-35f3-4c3d-a2a2-7291f9ef32e6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://data.europa.eu/m8g/Cost> .
<http://data.lblod.info/id/cost/6c9c0939-35f3-4c3d-a2a2-7291f9ef32e6> <http://www.w3.org/ns/shacl#order> "1"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://data.lblod.info/id/public-service/e73305b1-3e39-4de0-8ec2-bd58e582f900> <http://data.europa.eu/m8g/hasCompetentAuthority> <https://data.vlaanderen.be/id/organisatie/OVO027312> .
<http://data.lblod.info/id/public-service/e73305b1-3e39-4de0-8ec2-bd58e582f900> <http://data.europa.eu/m8g/hasCost> <http://data.lblod.info/id/cost/6c9c0939-35f3-4c3d-a2a2-7291f9ef32e6> .
<http://data.lblod.info/id/public-service/e73305b1-3e39-4de0-8ec2-bd58e582f900> <http://data.europa.eu/m8g/hasLegalResource> <https://codex.vlaanderen.be/Zoeken/Document.aspx?DID=1021563&param=informatie&ref=search&AVIDS=> .
<http://data.lblod.info/id/public-service/e73305b1-3e39-4de0-8ec2-bd58e582f900> <http://data.europa.eu/m8g/thematicArea> <https://productencatalogus.data.vlaanderen.be/id/concept/Thema/EconomieWerk> .
<http://data.lblod.info/id/public-service/e73305b1-3e39-4de0-8ec2-bd58e582f900> <http://mu.semte.ch/vocabularies/core/uuid> "1b10d73d-694b-4ff2-afd8-7df774489c2f" .
<http://data.lblod.info/id/public-service/e73305b1-3e39-4de0-8ec2-bd58e582f900> <http://purl.org/dc/terms/description> "<p>Voor het aanbieden van kansspelen in een drankgelegenheid (kansspelinrichting klasse III) hebt u een vergunning C nodig. Die vergunning moet u aanvragen bij de kansspelcommissie. </p>"@nl .
<http://data.lblod.info/id/public-service/e73305b1-3e39-4de0-8ec2-bd58e582f900> <http://purl.org/dc/terms/description> "<p>You are required to have a category C licence for games of chance in drinking establishments (Class III gaming establishments). You must apply for this licence with the Gaming Commission.</p>"@en .
<http://data.lblod.info/id/public-service/e73305b1-3e39-4de0-8ec2-bd58e582f900> <http://purl.org/dc/terms/source> <https://ipdc.vlaanderen.be/id/concept/3a9a7aa8-1260-4d04-9287-575a8f38389d> .
<http://data.lblod.info/id/public-service/e73305b1-3e39-4de0-8ec2-bd58e582f900> <http://purl.org/dc/terms/title> "Category C licence for games of chance in drinking establishments (Class III gaming establishments)"@en .
<http://data.lblod.info/id/public-service/e73305b1-3e39-4de0-8ec2-bd58e582f900> <http://purl.org/dc/terms/title> "Vergunning C voor kansspelen in drankgelegenheden (kansspelinrichtingen klasse III)"@nl .
<http://data.lblod.info/id/public-service/e73305b1-3e39-4de0-8ec2-bd58e582f900> <http://purl.org/dc/terms/type> <https://productencatalogus.data.vlaanderen.be/id/concept/Type/Toelating> .
<http://data.lblod.info/id/public-service/e73305b1-3e39-4de0-8ec2-bd58e582f900> <http://purl.org/vocab/cpsv#follows> <http://data.lblod.info/id/rule/3f0d4b6d-1749-450c-91ae-db2b35695e7b> .
<http://data.lblod.info/id/public-service/e73305b1-3e39-4de0-8ec2-bd58e582f900> <http://vocab.belgif.be/ns/publicservice#hasRequirement> <http://data.lblod.info/id/requirement/1dfc355e-3129-40d4-89a0-23640cbdb832> .
<http://data.lblod.info/id/public-service/e73305b1-3e39-4de0-8ec2-bd58e582f900> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.org/vocab/cpsv#PublicService> .
<http://data.lblod.info/id/public-service/e73305b1-3e39-4de0-8ec2-bd58e582f900> <http://www.w3.org/2000/01/rdf-schema#seeAlso> <http://data.lblod.info/id/website/5a353232-d3aa-41ed-a531-b53cf212085b> .
<http://data.lblod.info/id/public-service/e73305b1-3e39-4de0-8ec2-bd58e582f900> <http://www.w3.org/ns/dcat#keyword> "bingo"@en .
<http://data.lblod.info/id/public-service/e73305b1-3e39-4de0-8ec2-bd58e582f900> <http://www.w3.org/ns/dcat#keyword> "bingo"@nl .
<http://data.lblod.info/id/public-service/e73305b1-3e39-4de0-8ec2-bd58e582f900> <http://www.w3.org/ns/dcat#keyword> "caféspelen"@en .
<http://data.lblod.info/id/public-service/e73305b1-3e39-4de0-8ec2-bd58e582f900> <http://www.w3.org/ns/dcat#keyword> "caféspelen"@nl .
<http://data.lblod.info/id/public-service/e73305b1-3e39-4de0-8ec2-bd58e582f900> <http://www.w3.org/ns/dcat#keyword> "kansspel"@en .
<http://data.lblod.info/id/public-service/e73305b1-3e39-4de0-8ec2-bd58e582f900> <http://www.w3.org/ns/dcat#keyword> "kansspel"@nl .
<http://data.lblod.info/id/public-service/e73305b1-3e39-4de0-8ec2-bd58e582f900> <http://www.w3.org/ns/dcat#keyword> "kansspelen"@en .
<http://data.lblod.info/id/public-service/e73305b1-3e39-4de0-8ec2-bd58e582f900> <http://www.w3.org/ns/dcat#keyword> "kansspelen"@nl .
<http://data.lblod.info/id/public-service/e73305b1-3e39-4de0-8ec2-bd58e582f900> <http://www.w3.org/ns/dcat#keyword> "one ball’s"@en .
<http://data.lblod.info/id/public-service/e73305b1-3e39-4de0-8ec2-bd58e582f900> <http://www.w3.org/ns/dcat#keyword> "one ball’s"@nl .
<http://data.lblod.info/id/public-service/e73305b1-3e39-4de0-8ec2-bd58e582f900> <http://www.w3.org/ns/dcat#keyword> "one-ball"@en .
<http://data.lblod.info/id/public-service/e73305b1-3e39-4de0-8ec2-bd58e582f900> <http://www.w3.org/ns/dcat#keyword> "one-ball"@nl .
<http://data.lblod.info/id/public-service/e73305b1-3e39-4de0-8ec2-bd58e582f900> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#competentAuthorityLevel> <https://productencatalogus.data.vlaanderen.be/id/concept/BevoegdBestuursniveau/Federaal> .
<http://data.lblod.info/id/public-service/e73305b1-3e39-4de0-8ec2-bd58e582f900> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#competentAuthorityLevel> <https://productencatalogus.data.vlaanderen.be/id/concept/BevoegdBestuursniveau/Lokaal> .
<http://data.lblod.info/id/public-service/e73305b1-3e39-4de0-8ec2-bd58e582f900> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#conceptTag> <https://productencatalogus.data.vlaanderen.be/id/concept/ConceptTag/YourEuropeVerplicht> .
<http://data.lblod.info/id/public-service/e73305b1-3e39-4de0-8ec2-bd58e582f900> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#executingAuthorityLevel> <https://productencatalogus.data.vlaanderen.be/id/concept/UitvoerendBestuursniveau/Federaal> .
<http://data.lblod.info/id/public-service/e73305b1-3e39-4de0-8ec2-bd58e582f900> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#executingAuthorityLevel> <https://productencatalogus.data.vlaanderen.be/id/concept/UitvoerendBestuursniveau/Lokaal> .
<http://data.lblod.info/id/public-service/e73305b1-3e39-4de0-8ec2-bd58e582f900> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#publicationMedium> <https://productencatalogus.data.vlaanderen.be/id/concept/PublicatieKanaal/YourEurope> .
<http://data.lblod.info/id/public-service/e73305b1-3e39-4de0-8ec2-bd58e582f900> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#regulation> "<ul>\n	<li>Act of 7 May 1999 on gaming, betting, gaming establishments, and the protection of players, amended by the Act of 7 May 2019</li>\n	<li>Royal Decree of 22 December 2000 on the operation and management of Class III gaming establishments, the method of application, and the format of a category C licence</li>\n	<li>Royal Decree of 2 March 2004 establishing the list of games of chance the operation of which is permitted in Class III gaming establishments</li>\n</ul>"@en .
<http://data.lblod.info/id/public-service/e73305b1-3e39-4de0-8ec2-bd58e582f900> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#regulation> "<ul>\n	<li>\n	<p>Wet van 7 mei 1999 op de kansspelen, de weddenschappen, de kansspelinrichtingen en de bescherming van de spelers, gewijzigd bij wet van 7 mei 2019 </p>\n	</li>\n	<li>\n	<p>Koninklijk besluit van 22 december 2000 betreffende de werking en het beheer van de kansspelinrichtingen klasse III, de wijze van aanvraag en de vorm van een vergunning klasse C </p>\n	</li>\n	<li>\n	<p>Koninklijk besluit van 2 maart 2004 tot vaststelling van de lijst van de kansspelen waarvan de exploitatie is toegelaten in de kansspelinrichtingen klasse III</p>\n	</li>\n</ul>"@nl .
<http://data.lblod.info/id/public-service/e73305b1-3e39-4de0-8ec2-bd58e582f900> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#targetAudience> <https://productencatalogus.data.vlaanderen.be/id/concept/Doelgroep/Onderneming> .
<http://data.lblod.info/id/public-service/e73305b1-3e39-4de0-8ec2-bd58e582f900> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#targetAudience> <https://productencatalogus.data.vlaanderen.be/id/concept/Doelgroep/Organisatie> .
<http://data.lblod.info/id/public-service/e73305b1-3e39-4de0-8ec2-bd58e582f900> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#yourEuropeCategory> <https://productencatalogus.data.vlaanderen.be/id/concept/YourEuropeCategorie/DienstenLicentiesVergunningen> .
<http://data.lblod.info/id/requirement/1dfc355e-3129-40d4-89a0-23640cbdb832> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://data.europa.eu/m8g/Requirement> .
<http://data.lblod.info/id/requirement/1dfc355e-3129-40d4-89a0-23640cbdb832> <http://www.w3.org/ns/shacl#order> "1"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://data.lblod.info/id/rule/3f0d4b6d-1749-450c-91ae-db2b35695e7b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.org/vocab/cpsv#Rule> .
<http://data.lblod.info/id/rule/3f0d4b6d-1749-450c-91ae-db2b35695e7b> <http://www.w3.org/ns/shacl#order> "1"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://data.lblod.info/id/website/5a353232-d3aa-41ed-a531-b53cf212085b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/WebSite> .
<http://data.lblod.info/id/website/5a353232-d3aa-41ed-a531-b53cf212085b> <http://www.w3.org/ns/shacl#order> "1"^^<http://www.w3.org/2001/XMLSchema#integer> .
}