DELETE {
    GRAPH ?bestuurseenheidGraph {
        ?instance <http://mu.semte.ch/vocabularies/ext/reviewStatus> <http://lblod.data.gift/concepts/cf22e8d1-23c3-45da-89bc-00826eaf23c3> .
    }
}
INSERT {
    GRAPH ?bestuurseenheidGraph {
        ?instance <http://mu.semte.ch/vocabularies/ext/reviewStatus> <http://lblod.data.gift/concepts/review-status/concept-gearchiveerd> .
    }
}
WHERE {
    GRAPH ?bestuurseenheidGraph {
        ?instance a <http://purl.org/vocab/cpsv#PublicService> .
        ?instance <http://mu.semte.ch/vocabularies/ext/reviewStatus> <http://lblod.data.gift/concepts/cf22e8d1-23c3-45da-89bc-00826eaf23c3> .
    }

    FILTER(
    STRSTARTS(STR(?bestuurseenheidGraph), "http://mu.semte.ch/graphs/organizations/") &&
    STRENDS(STR(?bestuurseenheidGraph), "/LoketLB-LPDCGebruiker")
    )
}