DELETE {
  GRAPH ?graph{
    ?instance <http://data.europa.eu/m8g/hasLegalResource> ?legalResourceUrl.
  }
}

WHERE {
  GRAPH ?graph {
    ?instance a <http://purl.org/vocab/cpsv#PublicService>.
    ?instance <http://data.europa.eu/m8g/hasLegalResource> ?legalResourceUrl.
  }
}
