INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/b5a995382b4d908862d8203045a669c3d058553c16a4e2370030a012cf5f74bf/LoketLB-LPDCGebruiker> {

<http://data.lblod.info/id/public-service/88dbef16-5453-4c49-bbb3-163366ddcad5>	<https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#additionalDescription>	"<p>De grootte van de steun en de vorm waarin deze verleend wordt, kan verschillen. </p><p> </p>"@nl .
<http://data.lblod.info/id/bestuurseenheden/b5a995382b4d908862d8203045a669c3d058553c16a4e2370030a012cf5f74bf>	<http://www.w3.org/2004/02/skos/core#prefLabel>	"Oostrozebeke" .
<http://data.lblod.info/id/public-service/88dbef16-5453-4c49-bbb3-163366ddcad5>	<http://schema.org/dateCreated>	"2024-02-05T08:38:54.186Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
<http://data.lblod.info/id/bestuurseenheden/b5a995382b4d908862d8203045a669c3d058553c16a4e2370030a012cf5f74bf>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://data.vlaanderen.be/ns/besluit#Bestuurseenheid> .
<https://productencatalogus.data.vlaanderen.be/id/concept/Thema/WelzijnGezondheid>	<http://www.w3.org/2004/02/skos/core#prefLabel>	"Welzijn en Gezondheid"@nl .
<http://data.lblod.info/id/public-service/88dbef16-5453-4c49-bbb3-163366ddcad5>	<https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#targetAudience>	<https://productencatalogus.data.vlaanderen.be/id/concept/Doelgroep/Burger> .
<http://data.lblod.info/id/bestuurseenheden/b5a995382b4d908862d8203045a669c3d058553c16a4e2370030a012cf5f74bf>	<http://data.vlaanderen.be/ns/besluit#classificatie>	<http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000002> .
<http://data.lblod.info/id/public-service/88dbef16-5453-4c49-bbb3-163366ddcad5>	<http://purl.org/pav/createdBy>	<http://data.lblod.info/id/bestuurseenheden/b5a995382b4d908862d8203045a669c3d058553c16a4e2370030a012cf5f74bf> .
<http://data.lblod.info/id/public-service/88dbef16-5453-4c49-bbb3-163366ddcad5>	<http://data.europa.eu/m8g/hasCompetentAuthority>	<http://data.lblod.info/id/bestuurseenheden/b5a995382b4d908862d8203045a669c3d058553c16a4e2370030a012cf5f74bf> .
<http://data.lblod.info/id/public-service/88dbef16-5453-4c49-bbb3-163366ddcad5>	<http://purl.org/dc/terms/title>	"Financi\u00EBle tegemoetkoming voor de aankoop van eerste leeftijdsmelk"@nl .
<https://productencatalogus.data.vlaanderen.be/id/concept/BevoegdBestuursniveau/Lokaal>	<http://www.w3.org/2004/02/skos/core#prefLabel>	"Lokale overheid"@nl .
<http://data.lblod.info/id/public-service/88dbef16-5453-4c49-bbb3-163366ddcad5>	<http://purl.org/dc/terms/language>	<http://publications.europa.eu/resource/authority/language/NLD> .
<https://productencatalogus.data.vlaanderen.be/id/concept/Doelgroep/Burger>	<http://www.w3.org/2004/02/skos/core#prefLabel>	"Burger"@nl .
<http://data.lblod.info/id/public-service/88dbef16-5453-4c49-bbb3-163366ddcad5>	<http://purl.org/dc/terms/source>	<https://ipdc.vlaanderen.be/id/instantie/88dbef16-5453-4c49-bbb3-163366ddcad5> .
<http://data.lblod.info/id/public-service/88dbef16-5453-4c49-bbb3-163366ddcad5>	<https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#additionalDescription>	"<p>De grootte van de steun en de vorm waarin deze verleend wordt, kan verschillen. </p><p> </p>"@nl .
<https://productencatalogus.data.vlaanderen.be/id/concept/UitvoerendBestuursniveau/Lokaal>	<http://www.w3.org/2004/02/skos/core#prefLabel>	"Lokale overheid"@nl .
<https://productencatalogus.data.vlaanderen.be/id/concept/Type/FinancieelVoordeel>	<http://www.w3.org/2004/02/skos/core#prefLabel>	"Financieel voordeel"@nl .
<http://data.lblod.info/id/public-service/88dbef16-5453-4c49-bbb3-163366ddcad5>	<https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#executingAuthorityLevel>	<https://productencatalogus.data.vlaanderen.be/id/concept/UitvoerendBestuursniveau/Lokaal> .
<http://data.lblod.info/id/public-service/88dbef16-5453-4c49-bbb3-163366ddcad5>	<http://schema.org/productID>	"42841"^^<http://www.w3.org/2001/XMLSchema#string> .
<http://data.lblod.info/id/public-service/88dbef16-5453-4c49-bbb3-163366ddcad5>	<https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#hasExecutingAuthority>	<http://data.lblod.info/id/bestuurseenheden/b5a995382b4d908862d8203045a669c3d058553c16a4e2370030a012cf5f74bf> .
<http://data.lblod.info/id/public-service/88dbef16-5453-4c49-bbb3-163366ddcad5>	<https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#additionalDescription>	"<p>De grootte van de steun en de vorm waarin deze verleend wordt, kan verschillen. </p><p> </p>"@nl .
<http://data.lblod.info/id/public-service/88dbef16-5453-4c49-bbb3-163366ddcad5>	<https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#competentAuthorityLevel>	<https://productencatalogus.data.vlaanderen.be/id/concept/BevoegdBestuursniveau/Lokaal> .
<http://data.lblod.info/id/public-service/88dbef16-5453-4c49-bbb3-163366ddcad5>	<https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#dutchLanguageVariant>	"nl" .
<http://data.lblod.info/id/public-service/88dbef16-5453-4c49-bbb3-163366ddcad5>	<http://purl.org/dc/terms/description>	"<p>Als je voldoet aan bepaalde voorwaarden, kan je een financi\u00EBle steun krijgen voor het aanschaffen van eerste leeftijdsmelk.</p>"@nl .
<http://data.lblod.info/id/public-service/88dbef16-5453-4c49-bbb3-163366ddcad5>	<http://mu.semte.ch/vocabularies/core/uuid>	"88dbef16-5453-4c49-bbb3-163366ddcad5" .
<http://data.lblod.info/id/public-service/88dbef16-5453-4c49-bbb3-163366ddcad5>	<http://mu.semte.ch/vocabularies/ext/hasVersionedSource>	<https://ipdc.vlaanderen.be/id/instantie/88dbef16-5453-4c49-bbb3-163366ddcad5> .
<http://data.lblod.info/id/public-service/88dbef16-5453-4c49-bbb3-163366ddcad5>	<http://purl.org/dc/terms/type>	<https://productencatalogus.data.vlaanderen.be/id/concept/Type/FinancieelVoordeel> .
<http://data.lblod.info/id/public-service/88dbef16-5453-4c49-bbb3-163366ddcad5>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#InstancePublicService> .
<http://publications.europa.eu/resource/authority/language/NLD>	<http://www.w3.org/2004/02/skos/core#prefLabel>	"Nederlands"@nl .
<http://data.lblod.info/id/public-service/88dbef16-5453-4c49-bbb3-163366ddcad5>	<http://data.europa.eu/m8g/thematicArea>	<https://productencatalogus.data.vlaanderen.be/id/concept/Thema/WelzijnGezondheid> .
<http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000002>	<http://www.w3.org/2004/02/skos/core#prefLabel>	"OCMW" .

<http://mu.semte.ch/blank#b546212b-d99d-443e-941d-056f49d433e0>	<http://purl.org/dc/terms/title>	"Bewijs"@nl .
<http://mu.semte.ch/blank#4da6f1e6-a297-4146-b512-9530e277139b>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://data.europa.eu/m8g/Requirement> .
<http://mu.semte.ch/blank#b546212b-d99d-443e-941d-056f49d433e0>	<http://purl.org/dc/terms/description>	"<p>Best breng je, bij het eerste contact met het OCMW, al jouw identiteitskaart mee.</p><p>Het is mogelijk dat de maatschappelijk werker je nog andere documenten vraagt.</p>"@nl .
<http://mu.semte.ch/blank#2fa658d9-1620-4e4b-aa9c-13656baaa074>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.org/vocab/cpsv#Rule> .
<http://mu.semte.ch/blank#2fa658d9-1620-4e4b-aa9c-13656baaa074>	<http://purl.org/dc/terms/description>	"<ul><li>Neem contact op met het OCMW en zeg dat je komt voor de financi\u00EBle tegemoetkoming voor de aankoop van eerste leeftijdsmelk.</li><li>Een maatschappelijk werker zal je ontvangen en, samen met jou, jouw situatie en jouw vraag bekijken.</li><li>In sommige gevallen, zal de maatschappelijk werker een sociaal onderzoek doen.</li><li>De maatschappelijk werker gaat bekijken welke dienstverlening van het OCMW voor je het meest passend is. Hij gaat je eventueel een voorstel doen, waarop je kan ingaan.</li></ul>"@nl .
<http://mu.semte.ch/blank#b546212b-d99d-443e-941d-056f49d433e0>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://data.europa.eu/m8g/Evidence> .
<http://mu.semte.ch/blank#4da6f1e6-a297-4146-b512-9530e277139b>	<http://purl.org/dc/terms/description>	"<ul><li>Je hebt een pasgeboren baby.</li><li>Je hebt onvoldoende financi\u00EBle middelen. Dit wordt individueel bepaald.</li></ul>"@nl .
<http://mu.semte.ch/blank#4da6f1e6-a297-4146-b512-9530e277139b>	<http://purl.org/dc/terms/title>	"Voorwaarden"@nl .
<http://mu.semte.ch/blank#2fa658d9-1620-4e4b-aa9c-13656baaa074>	<http://www.w3.org/ns/shacl#order>	"0"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://data.lblod.info/id/public-service/88dbef16-5453-4c49-bbb3-163366ddcad5>	<http://vocab.belgif.be/ns/publicservice#hasRequirement>	<http://mu.semte.ch/blank#4da6f1e6-a297-4146-b512-9530e277139b> .
<http://mu.semte.ch/blank#b546212b-d99d-443e-941d-056f49d433e0>	<http://mu.semte.ch/vocabularies/core/uuid>	"12d17800-7a86-11f1-9c10-d9d20570fa93" .
<http://mu.semte.ch/blank#2fa658d9-1620-4e4b-aa9c-13656baaa074>	<http://mu.semte.ch/vocabularies/core/uuid>	"deea1d80-7a85-11f1-9c10-d9d20570fa93" .
<http://mu.semte.ch/blank#2fa658d9-1620-4e4b-aa9c-13656baaa074>	<http://purl.org/dc/terms/title>	"Procedure"@nl .
<http://mu.semte.ch/blank#4da6f1e6-a297-4146-b512-9530e277139b>	<http://mu.semte.ch/vocabularies/core/uuid>	"f233dc00-7a85-11f1-9c10-d9d20570fa93" .
<http://mu.semte.ch/blank#4da6f1e6-a297-4146-b512-9530e277139b>	<http://www.w3.org/ns/shacl#order>	"0"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://data.lblod.info/id/public-service/88dbef16-5453-4c49-bbb3-163366ddcad5>	<http://purl.org/vocab/cpsv#follows>	<http://mu.semte.ch/blank#2fa658d9-1620-4e4b-aa9c-13656baaa074> .
<http://mu.semte.ch/blank#4da6f1e6-a297-4146-b512-9530e277139b>	<http://data.europa.eu/m8g/hasSupportingEvidence>	<http://mu.semte.ch/blank#b546212b-d99d-443e-941d-056f49d433e0> .

<http://mu.semte.ch/blank#b22441bd-c2a6-4bc4-9ade-2588a71148ec>	<http://schema.org/email>	"sociaalhuis@oostrozebeke.be"^^<http://www.w3.org/2001/XMLSchema#string> .
<http://mu.semte.ch/blank#b22441bd-c2a6-4bc4-9ade-2588a71148ec>	<https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#address>	<http://mu.semte.ch/blank#0436c15f-91aa-4238-b5f3-b6736e585ffd> .
<http://mu.semte.ch/blank#b22441bd-c2a6-4bc4-9ade-2588a71148ec>	<http://schema.org/openingHours>	"Elke werkdag van 9 u. tot 12 u. en op dinsdag van 16.30 en 18 u. zonder afspraak en van 13.30 tot 16.30 met afspraak."^^<http://www.w3.org/2001/XMLSchema#string> .
<http://mu.semte.ch/blank#b22441bd-c2a6-4bc4-9ade-2588a71148ec>	<http://schema.org/telephone>	"056/67 11 50"^^<http://www.w3.org/2001/XMLSchema#string> .
<http://mu.semte.ch/blank#0436c15f-91aa-4238-b5f3-b6736e585ffd>	<https://data.vlaanderen.be/ns/adres#Straatnaam>	"Ernest Brengierstraat"@nl .
<http://mu.semte.ch/blank#0436c15f-91aa-4238-b5f3-b6736e585ffd>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/ns/locn#Address> .
<http://mu.semte.ch/blank#b22441bd-c2a6-4bc4-9ade-2588a71148ec>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://schema.org/ContactPoint> .
<http://mu.semte.ch/blank#b22441bd-c2a6-4bc4-9ade-2588a71148ec>	<http://mu.semte.ch/vocabularies/core/uuid>	"1fd42840-7a86-11f1-9c10-d9d20570fa93" .
<http://mu.semte.ch/blank#0436c15f-91aa-4238-b5f3-b6736e585ffd>	<https://data.vlaanderen.be/ns/adres#gemeentenaam>	"Oostrozebeke"@nl .
<http://mu.semte.ch/blank#b22441bd-c2a6-4bc4-9ade-2588a71148ec>	<http://www.w3.org/ns/shacl#order>	"0"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://mu.semte.ch/blank#0436c15f-91aa-4238-b5f3-b6736e585ffd>	<https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer>	"6"^^<http://www.w3.org/2001/XMLSchema#string> .
<http://mu.semte.ch/blank#0436c15f-91aa-4238-b5f3-b6736e585ffd>	<http://mu.semte.ch/vocabularies/core/uuid>	"1fd42840-7a86-11f1-9c10-d9d20570fa93" .
<http://data.lblod.info/id/public-service/88dbef16-5453-4c49-bbb3-163366ddcad5>	<http://data.europa.eu/m8g/hasContactPoint>	<http://mu.semte.ch/blank#b22441bd-c2a6-4bc4-9ade-2588a71148ec> .
<http://mu.semte.ch/blank#b22441bd-c2a6-4bc4-9ade-2588a71148ec>	<http://schema.org/url>	"https://www.oostrozebeke.be/sociaalhuis"^^<http://www.w3.org/2001/XMLSchema#string> .

<http://mu.semte.ch/blank#0436c15f-91aa-4238-b5f3-b6736e585ffd>	<https://data.vlaanderen.be/ns/adres#land>	"Belgi\u00EB"@nl .
<http://mu.semte.ch/blank#0436c15f-91aa-4238-b5f3-b6736e585ffd>	<https://data.vlaanderen.be/ns/adres#postcode>	"8780" .
<http://mu.semte.ch/blank#0436c15f-91aa-4238-b5f3-b6736e585ffd>	<https://data.vlaanderen.be/ns/adres#verwijstNaar>	<https://data.vlaanderen.be/id/adres/1163413> .

  }
}