INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/353234a365664e581db5c2f7cc07add2534b47b8e1ab87c821fc6e6365e6bef5/LoketLB-LPDCGebruiker> {

<http://data.lblod.info/id/bestuurseenheden/353234a365664e581db5c2f7cc07add2534b47b8e1ab87c821fc6e6365e6bef5>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://data.vlaanderen.be/ns/besluit#Bestuurseenheid> .
<https://stad.gent/id/product/ca6ff490-10b2-ea11-a853-005056a8c14b>	<http://data.europa.eu/m8g/hasCompetentAuthority>	<http://data.lblod.info/id/bestuurseenheden/353234a365664e581db5c2f7cc07add2534b47b8e1ab87c821fc6e6365e6bef5> .
<https://stad.gent/id/product/ca6ff490-10b2-ea11-a853-005056a8c14b>	<http://mu.semte.ch/vocabularies/ext/hasVersionedSource>	<https://ipdc.vlaanderen.be/id/instantie/ca6ff490-10b2-ea11-a853-005056a8c14b> .
<https://stad.gent/id/product/ca6ff490-10b2-ea11-a853-005056a8c14b>	<http://purl.org/dc/terms/source>	<https://ipdc.vlaanderen.be/id/instantie/ca6ff490-10b2-ea11-a853-005056a8c14b> .
<https://productencatalogus.data.vlaanderen.be/id/concept/BevoegdBestuursniveau/Lokaal>	<http://www.w3.org/2004/02/skos/core#prefLabel>	"Lokale overheid"@nl-be-x-informal .
<https://stad.gent/id/product/ca6ff490-10b2-ea11-a853-005056a8c14b>	<https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#executingAuthorityLevel>	<https://productencatalogus.data.vlaanderen.be/id/concept/UitvoerendBestuursniveau/Lokaal> .
<https://productencatalogus.data.vlaanderen.be/id/concept/UitvoerendBestuursniveau/Lokaal>	<http://www.w3.org/2004/02/skos/core#prefLabel>	"Lokale overheid"@nl-be-x-informal .
<https://stad.gent/id/product/ca6ff490-10b2-ea11-a853-005056a8c14b>	<https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#additionalDescription>	"Ben je binnenkort 50 jaar getrouwd of vier je nog een ander huwelijksjubileum? Vraag een huldiging aan bij de stad."@nl-be-x-informal .
<https://stad.gent/id/product/ca6ff490-10b2-ea11-a853-005056a8c14b>	<http://purl.org/dc/terms/language>	<http://publications.europa.eu/resource/authority/language/NLD> .
<https://stad.gent/id/product/ca6ff490-10b2-ea11-a853-005056a8c14b>	<https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#hasExecutingAuthority>	<http://data.lblod.info/id/bestuurseenheden/353234a365664e581db5c2f7cc07add2534b47b8e1ab87c821fc6e6365e6bef5> .
<https://stad.gent/id/product/ca6ff490-10b2-ea11-a853-005056a8c14b>	<https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#competentAuthorityLevel>	<https://productencatalogus.data.vlaanderen.be/id/concept/BevoegdBestuursniveau/Lokaal> .
<http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000001>	<http://www.w3.org/2004/02/skos/core#prefLabel>	"Gemeente" .
<https://stad.gent/id/product/ca6ff490-10b2-ea11-a853-005056a8c14b>	<http://schema.org/productID>	"50605"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://stad.gent/id/product/ca6ff490-10b2-ea11-a853-005056a8c14b>	<http://purl.org/dc/terms/description>	"<p>Het Gentse stadsbestuur biedt gratis huldigingen aan aan Gentse echtparen die hun huwelijksverjaardag vieren. Je kunt de viering aanvragen voor jezelf of voor een familielid.</p><ul></ul>"@nl-be-x-informal .
<http://data.lblod.info/id/bestuurseenheden/353234a365664e581db5c2f7cc07add2534b47b8e1ab87c821fc6e6365e6bef5>	<http://www.w3.org/2004/02/skos/core#prefLabel>	"Gent" .
<https://stad.gent/id/product/ca6ff490-10b2-ea11-a853-005056a8c14b>	<http://schema.org/dateCreated>	"2020-06-19T09:38:11Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
<https://stad.gent/id/product/ca6ff490-10b2-ea11-a853-005056a8c14b>	<https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#dutchLanguageVariant>	"nl-be-x-informal" .
<https://stad.gent/id/product/ca6ff490-10b2-ea11-a853-005056a8c14b>	<http://purl.org/dc/terms/title>	"Huwelijksjubileum vieren"@nl-be-x-informal .
<https://stad.gent/id/product/ca6ff490-10b2-ea11-a853-005056a8c14b>	<http://mu.semte.ch/vocabularies/core/uuid>	"ca6ff490-10b2-ea11-a853-005056a8c14b" .
<https://stad.gent/id/product/ca6ff490-10b2-ea11-a853-005056a8c14b>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#InstancePublicService> .
<http://publications.europa.eu/resource/authority/language/NLD>	<http://www.w3.org/2004/02/skos/core#prefLabel>	"Nederlands"@nl-be-x-informal .
<https://stad.gent/id/product/ca6ff490-10b2-ea11-a853-005056a8c14b>	<http://purl.org/pav/createdBy>	<http://data.lblod.info/id/bestuurseenheden/353234a365664e581db5c2f7cc07add2534b47b8e1ab87c821fc6e6365e6bef5> .
<http://data.lblod.info/id/bestuurseenheden/353234a365664e581db5c2f7cc07add2534b47b8e1ab87c821fc6e6365e6bef5>	<http://data.vlaanderen.be/ns/besluit#classificatie>	<http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000001> .

<https://stad.gent/id/product/ca6ff490-10b2-ea11-a853-005056a8c14b> <http://www.w3.org/ns/adms#status>	<http://lblod.data.gift/concepts/instance-status/verzonden>
  }
}