(define-resource feedback ()
  :class (s-prefix "schema2:Conversation")
  :properties `((:created-at :datetime ,(s-prefix "schema2:dateCreated"))
                (:productnummer :string ,(s-prefix "schema2:productID"))
                (:lpdc-instance-derived-uri :uri ,(s-prefix "schema2:about")))
  :has-one `((concept :via ,(s-prefix "adms:status")
                      :as "status")
             (concept :via ,(s-prefix "schema2:actionStatus")
                                            :as "verwerking-status")
             (feedback-vraag :via ,(s-prefix "schema2:question")
                             :as "vraag")
             (feedback-antwoord :via ,(s-prefix "schema2:suggestedAnswer")
                                :as "antwoord")
             (public-service :via ,(s-prefix "skos:primarySubject")
                             :as "instantie"))
  :resource-base (s-url "https://ipdc.vlaanderen.be/publicatie/id/feedback/")
  :features '(include-uri)
  :on-path "feedbacks"
)

(define-resource feedback-vraag ()
  :class (s-prefix "schema2:AskAction")
  :properties `((:vraag :string ,(s-prefix "schema2:question"))
                (:timestamp :datetime ,(s-prefix "schema2:startTime"))
                (:van :uri ,(s-prefix "schema2:agent"))
                (:naar :uri ,(s-prefix "schema2:recipient")))
  :resource-base (s-url "https://ipdc.vlaanderen.be/publicatie/id/question/")
  :features '(include-uri)
  :on-path "feedback-vragen"
)

(define-resource feedback-antwoord ()
  :class (s-prefix "schema2:ReplyAction")
  :properties `((:antwoord :string ,(s-prefix "schema2:resultComment"))
                (:timestamp :datetime ,(s-prefix "schema2:startTime"))
                (:van :uri ,(s-prefix "schema2:agent"))
                (:naar :uri ,(s-prefix "schema2:recipient")))
  :resource-base (s-url "https://ipdc.vlaanderen.be/publicatie/id/answer/")
  :features '(include-uri)
  :on-path "feedback-antwoorden"
)

(define-resource feedback-snapshot ()
  :class (s-prefix "schema2:DataFeedItem")
  :properties `((:created-at :datetime ,(s-prefix "schema2:dateCreated")))
  :has-one `((feedback :via ,(s-prefix "schema2:item")
                       :as "feedback")
             (feedback :via ,(s-prefix "dct:isVersionOf")
                       :as "is-version-of"))
  :resource-base (s-url "https://ipdc.vlaanderen.be/publicatie/id/feedback-snapshot/")
  :features '(include-uri)
  :on-path "feedback-snapshots"
)