(define-resource feedback ()
  :class (s-prefix "schema2:Conversation")
  :properties `((:created-at :datetime ,(s-prefix "schema2:dateCreated"))
                (:productnummer :string ,(s-prefix "schema2:productID"))
                (:lpdc-instance-derived-uri :uri ,(s-prefix "schema2:about")))
  :has-one `((concept :via ,(s-prefix "adms:status")
                      :as "status")
             (concept :via ,(s-prefix "schema2:actionStatus")
                                            :as "processing-status")
             (concept :via ,(s-prefix "schema2:result")
                                            :as "processing-result")
             (feedback-question :via ,(s-prefix "schema2:question")
                             :as "question")
             (feedback-answer :via ,(s-prefix "schema2:suggestedAnswer")
                                :as "answer")
             (public-service :via ,(s-prefix "skos:primarySubject")
                             :as "instance"))
  :resource-base (s-url "https://ipdc.vlaanderen.be/publicatie/id/feedback/")
  :features '(include-uri)
  :on-path "feedbacks"
)

(define-resource feedback-question ()
  :class (s-prefix "schema2:AskAction")
  :properties `((:question :html ,(s-prefix "schema2:question"))
                (:timestamp :datetime ,(s-prefix "schema2:startTime"))
                (:from :uri ,(s-prefix "schema2:agent"))
                (:to :uri ,(s-prefix "schema2:recipient")))
  :resource-base (s-url "https://ipdc.vlaanderen.be/publicatie/id/question/")
  :features '(include-uri)
  :on-path "feedback-questions"
)

(define-resource feedback-answer ()
  :class (s-prefix "schema2:ReplyAction")
  :properties `((:answer :html ,(s-prefix "schema2:resultComment"))
                (:timestamp :datetime ,(s-prefix "schema2:startTime"))
                (:from :uri ,(s-prefix "schema2:agent"))
                (:to :uri ,(s-prefix "schema2:recipient")))
  :resource-base (s-url "https://ipdc.vlaanderen.be/publicatie/id/answer/")
  :features '(include-uri)
  :on-path "feedback-answers"
)

(define-resource feedback-snapshot ()
  :class (s-prefix "schema2:DataFeedItem")
  :properties `((:created-at :datetime ,(s-prefix "schema2:dateCreated")))
  :has-one `((feedback :via ,(s-prefix "schema2:item")
                       :as "feedback")
             (feedback :via ,(s-prefix "dct:isVersionOf")
                       :as "is-version-of"))
  :resource-base (s-url "https://ipdc.vlaanderen.be/publicatie/id/feedback-snapshot/")
  :features '(include-uri)
  :on-path "feedback-snapshots"
)
