(define-resource notification-rule ()
  :class (s-prefix "lpdcExt:NotificationRule")
  :properties `((:label :string ,(s-prefix "skos:prefLabel"))
                (:description :string ,(s-prefix "skos:description")))
  :resource-base (s-url "http://data.lblod.info/id/notification-rules/")
  :features '(include-uri)
  :on-path "notification-rules")

(define-resource notification-preference ()
  :class (s-prefix "lpdcExt:NotificationPreference")
  :properties `((:frequency :string ,(s-prefix "lpdcExt:notificationFrequency"))
                (:notifications-enabled :boolean ,(s-prefix "lpdcExt:notificationsEnabled"))
                (:email-address :string ,(s-prefix "schema:email"))
                (:status-report-enabled :boolean ,(s-prefix "lpdcExt:statusReportEnabled"))
                (:last-notified-at :datetime ,(s-prefix "lpdcExt:lastNotifiedAt")))
  :has-many `((notification-rule :via ,(s-prefix "lpdcExt:hasEnabledRule")
                                 :as "enabled-rules")
              (notification-log :via ,(s-prefix "lpdcExt:hasLog")
                                :as "logs")
              (public-service :via ,(s-prefix "ext:notificationInstance")
                              :as "instances"))
  :has-one `((gebruiker :via ,(s-prefix "lpdcExt:hasNotificationPreference")
                        :inverse t
                        :as "gebruiker"))
  :resource-base (s-url "http://data.lblod.info/id/notification-preferences/")
  :features '(include-uri)
  :on-path "notification-preferences")