(define-resource subscription ()
  :class (s-prefix "ext:Subscription")
  :properties `((:subscription-frequency :string ,(s-prefix "ext:subscriptionFrequency"))
                (:subscription-active :boolean ,(s-prefix "ext:subscriptionActive"))
                (:email-address :string ,(s-prefix "ext:emailAddress"))
                (:scope :string ,(s-prefix "ext:scope"))
                (:status-report-enabled :boolean ,(s-prefix "ext:statusReportEnabled"))
                (:last-notified-at :datetime ,(s-prefix "lpdcExtext:lastNotifiedAt"))
                (:notify-feedback :boolean ,(s-prefix "lpdcExtext:notifyFeedback"))
                (:notify-review-status :boolean ,(s-prefix "lpdcExtext:notifyReviewStatus"))
                (:notify-formal-informal :boolean ,(s-prefix "lpdcExt:notifyFormalInformal")))
  :has-one `((gebruiker :via ,(s-prefix "dct:creator")
                        :as "creator"))
  :has-many `((public-service :via ,(s-prefix "ext:subscriptionInstance")
                              :as "instances"))
  :resource-base (s-url "http://data.lblod.info/id/subscriptions/")
  :features '(include-uri)
  :on-path "subscriptions")