(define-resource subscription ()
  :class (s-prefix "ext:Subscription")
  :properties `((:frequency :string ,(s-prefix "ext:subscriptionFrequency"))
                (:email-address :string ,(s-prefix "ext:mailAdresVoorNotificaties"))
                (:status-report-enabled :boolean ,(s-prefix "lpdcExt:statusReportEnabled"))
                (:last-notified-at :datetime ,(s-prefix "lpdcExt:lastNotifiedAt"))
                (:notify-feedback :boolean ,(s-prefix "lpdcExt:notifyFeedback"))
                (:notify-review-status :boolean ,(s-prefix "lpdcExt:notifyReviewStatus"))
                (:notify-formal-informal :boolean ,(s-prefix "lpdcExt:notifyFormalInformal")))
  :has-one `((gebruiker :via ,(s-prefix "lpdcExt:hasNotificationPreference")
                      :inverse t
                      :as "gebruiker"))
  :has-many `((public-service :via ,(s-prefix "ext:subscriptionInstance")
                              :as "instances"))
  :resource-base (s-url "http://data.lblod.info/id/subscriptions/")
  :features '(include-uri)
  :on-path "subscriptions")