DELETE {
  GRAPH ?bestuurseenheidGraph {
    ?instance ?p ?o.
  }
}
INSERT {
  GRAPH ?bestuurseenheidGraph {
    ?instance ?p ?newOLang.
  }
} WHERE {

VALUES (?oldUrl ?newUrl) {
('href="/bouwen-wonen-en-energie/bouwen-en-verbouwen/bouwvergunningen-en-plannen/melding-of-vrijstelling-van-vergunning-voor-kleine-bouwwerken"' 'href="https://www.vlaanderen.be/bouwen-wonen-en-energie/bouwen-en-verbouwen/bouwvergunningen-en-plannen/melding-of-vrijstelling-van-vergunning-voor-kleine-bouwwerken"')
}

  GRAPH ?bestuurseenheidGraph {
    ?instance ?p ?o.
  }
  BIND(LANG(?o) AS ?oLang)
  BIND(REPLACE(STR(?o), ?oldUrl, ?newUrl) as ?newO1)
  BIND(STRLANG(?newO1, ?oLang) as ?newOLang)


  FILTER(
    STRSTARTS(STR(?bestuurseenheidGraph), "http://mu.semte.ch/graphs/organizations/") &&
    STRENDS(STR(?bestuurseenheidGraph), "/LoketLB-LPDCGebruiker") &&
    regex(str(?o), ?oldUrl)
  )
}