DELETE {
  GRAPH ?bestuurseenheidGraph {
    ?instance ?p ?o.
  }
}
INSERT {
  GRAPH ?bestuurseenheidGraph {
    ?instance ?p ?newOLang.
  }
} WHERE {

VALUES (?oldUrl ?newUrl) {
('href="/veranderen-van-voornaam"' 'href="https://www.vlaanderen.be/veranderen-van-voornaam"')
}
  GRAPH ?bestuurseenheidGraph {
    ?instance ?p ?o.
  }
  BIND(LANG(?o) AS ?oLang)
  BIND(REPLACE(STR(?o), ?oldUrl, ?newUrl) as ?newO1)
  BIND(STRLANG(?newO1, ?oLang) as ?newOLang)


  FILTER(
    STRSTARTS(STR(?bestuurseenheidGraph), "http://mu.semte.ch/graphs/organizations/") &&
    STRENDS(STR(?bestuurseenheidGraph), "/LoketLB-LPDCGebruiker") &&
    regex(str(?o), ?oldUrl)
  )
}