
  DELETE DATA {
    GRAPH <http://mu.semte.ch/graphs/organizations/8ef1e4a43efd913e6b09b0ddea344b7b5d723a344ad559389a55ae1ff0bebc8f/LoketLB-LPDCGebruiker> {
      <http://data.lblod.info/id/public-service/3e395f18-1e9b-412d-b189-792ef30cacf3> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/c090100d-42d5-42f4-bf30-dac6a29ecb0a> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/a14b3963-da26-4424-a2cd-239b5f55d656> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/9b04c3d2-fdf4-4728-a179-78b4ecdb3f1e> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/50f46c74-db96-424f-a0b2-9e7963052b48> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/d4c29dbc-9460-443d-bfa1-519f47fc7209> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/6c8cef58-a9d9-4802-8c7c-e3ad370f776c> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/dbc93f3a-873f-408a-bb5e-3a4d0c6867e7> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/e454163e-0dda-48a1-8e38-2ff1bf7b2a1e> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/3bac8c4a-2b17-4648-8707-803d311c636b> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/9834edca-f985-4544-9afb-54703261a3f8> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/066ce561-0632-4527-9e40-b84da6185396> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/e0bd9230-55c4-44e3-93f3-d44f48fc9d6a> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/613f1fbd-083b-4ccd-bcb7-54dd1b89c2ff> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/14f9851a-db33-4de9-a3f4-075e818f4744> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/99033983-6452-44f5-bc3d-cb5b8a2e1744> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/765964b8-dc8f-4ade-b6a7-443edd24e85d> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/b4501bd0-35b0-449b-9f88-251862923e47> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/fffe12f3-26fd-4da7-87e1-7d9a79aa79bc> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/cde0efb3-bc65-4bf5-afdb-550eb8abbe86> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/9e817dfe-68d5-466b-853f-37b7210c06e7> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/b2f6bd20-e42c-44d6-8313-f4c2b874e918> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/033e07d3-c984-450b-b441-33fa316494c8> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/c4711b34-90b5-4fac-9fd9-c4e5aa3d5d22> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/5a3bbaeb-784d-4aa1-8db8-9dc9bb01a26d> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/76570abc-cd4f-4768-9ff5-8ceebba8d4dc> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/bebb40e6-e70b-41d5-b6ec-920cc62b4727> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/320788df-3a61-4caa-a28c-4bdeec2fd8ec> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/d7de902f-ff2b-4ae3-97b0-5e75cac51f72> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/ed07d6ef-e05b-43f9-bd6a-12d9d989c7ac> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/0a2fd3e6-6c17-4d61-9ad8-f13bb574296e> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/57189708-4bc3-42ec-ac77-03e62291e7fd> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/197d7bd5-f5c4-409f-8fd9-9288d8e61fe1> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/1f95e924-7426-4c9e-95bd-ec5b2aad6d44> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/39739225-f2ef-45bd-a4d7-88aeb88b0072> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/46caa7db-e0b7-44c8-9961-d578be0cc2d2> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/555ee8ce-5c85-4317-acba-70243c567682> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/59b4887c-8d59-403e-9985-69bb7d72e0ef> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/63b2ca4c-8412-4fe5-b91e-d8215ce9e4f5> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/676988b9-6d9f-4171-8f3a-4945b1617e65> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/76277c10-74c9-4340-8437-6afbf5454dbc> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/7b573a5b-d669-4596-8711-1cdd0c2075a4> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/7de06515-7331-437b-a9bd-75c2722722d1> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/8df2e6d3-2db7-402d-97f5-d107b30cbd73> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/96be4cd7-5372-4658-bec2-aa3bfa2cd716> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/98d5377a-4ca9-4223-bed3-8e2fc6e5a593> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/9a28f7f8-1614-4a92-9ca3-e72d7c35aae2> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/b1bfe3ef-8057-42b1-9cba-f778448457dc> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/b229613e-9f87-4183-97db-60e405692f38> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/d724daa8-5a6b-45ce-8f05-f35d134ae4e1> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/dc38ed77-8aa2-499b-acf4-86c52ffdc7b0> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/e910cf6a-64f4-4ef5-bab5-667315b04029> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/ee6914ff-e911-42ba-b1b2-35a56bcf5872> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/f3d5d5d7-c64f-43a4-9a20-5b7a5277a3d3> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/82236dd4-56c3-48ac-a0d7-667119959d56> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/12c6a838-78de-40d1-b3b8-0c554c5eb3a4> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/44fce966-42ee-4e7c-8d62-7403984ce433> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/30d80684-5d48-4bfa-b6ef-10d745ab1131> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/4ac1910c-dd05-496d-bb48-8797247849f8> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/ffd1d721-28f5-4660-b5fe-600b1425ae61> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/b93d393c-542d-48f8-9e68-4386f4c097d5> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/284aeb48-20e2-4017-835e-a8f52273760d> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/c267227f-f436-490a-8514-b856b1613bf7> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/cac78e8c-96f8-48d6-8517-e2d1247cb7c6> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/e0b0d1f4-3aca-4b1e-ad77-0ee92bbcafac> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/d286c450-c25f-4214-93b3-33ee714584ff> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/4fc67384-1740-4f8c-a14b-47062336cfc8> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/0bb48f75-9245-4605-a875-a63677f5b2b2> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/74146ed1-d4dc-403a-b4ac-f1c62fcf9b31> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/597e5f25-6520-4a5f-99ee-eadf3fa08c88> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/557891be-3329-4d13-afd9-b87dac82b127> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/b60cadee-2764-4532-8604-039dc3cbc8c6> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/ffbd917b-baa3-47cc-8995-230a48bed7f4> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/fb19e60b-2779-430a-875c-3b2933820181> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/0a802a9f-9d34-4901-898f-bd2af75897ef> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/988072ca-4e15-4d9b-bb28-2a20a36523b7> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/dad5339c-6d34-4d74-8bd5-3db5039061e8> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/a0145fd3-a806-46e1-8ac0-3b5caad0e156> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/8963371c-b4e3-494e-abe1-f786c71e3adf> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/4b847125-82b5-459f-ace9-80956618cf3a> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/4e39d98b-0bf9-477c-bc5b-420a87528993> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/b6b1cd19-0d1c-4f55-a13f-e348abf7b61e> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/2e1762af-2bf8-4584-bf8d-e8458fa86b39> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/dac4d875-c85e-4898-9c94-2b1e943e9200> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/dc76a384-5b51-4123-be0b-be3cc7da5ff9> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/381c9fad-4835-427e-80ae-1418974f73fb> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/49f3b95c-41bb-4945-a82d-330aedd18b62> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/f5f152c0-b877-428e-b6b9-3a0fae304bdd> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/a5d0e0a7-b0ac-4d37-a50d-ed82f8d4c172> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/0cd2c3e9-ee4f-4082-b3ca-66220eee94f0> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/ced19814-3b5c-41b0-bf99-7610a8d73005> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/0d3a88af-ff24-41c3-8149-43058b794dcd> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/ca144cd0-a22d-4e1b-afbf-2edb52e0077e> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/6e85808f-777f-42a6-b920-0a9cedf0c298> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/22c002bc-762a-492f-a38f-58352864a964> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/ca98fcf0-6c5f-40e7-a0e5-d96b29d0d141> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/e9e1f45a-86e2-4aa1-8204-065275957b7e> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
    }
  } INSERT DATA {
    GRAPH <http://mu.semte.ch/graphs/organizations/8ef1e4a43efd913e6b09b0ddea344b7b5d723a344ad559389a55ae1ff0bebc8f/LoketLB-LPDCGebruiker> {
      <http://data.lblod.info/id/public-service/3e395f18-1e9b-412d-b189-792ef30cacf3> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/c090100d-42d5-42f4-bf30-dac6a29ecb0a> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/a14b3963-da26-4424-a2cd-239b5f55d656> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/9b04c3d2-fdf4-4728-a179-78b4ecdb3f1e> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/50f46c74-db96-424f-a0b2-9e7963052b48> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/d4c29dbc-9460-443d-bfa1-519f47fc7209> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/6c8cef58-a9d9-4802-8c7c-e3ad370f776c> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/dbc93f3a-873f-408a-bb5e-3a4d0c6867e7> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/e454163e-0dda-48a1-8e38-2ff1bf7b2a1e> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/3bac8c4a-2b17-4648-8707-803d311c636b> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/9834edca-f985-4544-9afb-54703261a3f8> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/066ce561-0632-4527-9e40-b84da6185396> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/e0bd9230-55c4-44e3-93f3-d44f48fc9d6a> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/613f1fbd-083b-4ccd-bcb7-54dd1b89c2ff> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/14f9851a-db33-4de9-a3f4-075e818f4744> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/99033983-6452-44f5-bc3d-cb5b8a2e1744> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/765964b8-dc8f-4ade-b6a7-443edd24e85d> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/b4501bd0-35b0-449b-9f88-251862923e47> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/fffe12f3-26fd-4da7-87e1-7d9a79aa79bc> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/cde0efb3-bc65-4bf5-afdb-550eb8abbe86> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/9e817dfe-68d5-466b-853f-37b7210c06e7> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/b2f6bd20-e42c-44d6-8313-f4c2b874e918> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/033e07d3-c984-450b-b441-33fa316494c8> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/c4711b34-90b5-4fac-9fd9-c4e5aa3d5d22> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/5a3bbaeb-784d-4aa1-8db8-9dc9bb01a26d> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/76570abc-cd4f-4768-9ff5-8ceebba8d4dc> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/bebb40e6-e70b-41d5-b6ec-920cc62b4727> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/320788df-3a61-4caa-a28c-4bdeec2fd8ec> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/d7de902f-ff2b-4ae3-97b0-5e75cac51f72> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/ed07d6ef-e05b-43f9-bd6a-12d9d989c7ac> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/0a2fd3e6-6c17-4d61-9ad8-f13bb574296e> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/57189708-4bc3-42ec-ac77-03e62291e7fd> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/197d7bd5-f5c4-409f-8fd9-9288d8e61fe1> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/1f95e924-7426-4c9e-95bd-ec5b2aad6d44> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/39739225-f2ef-45bd-a4d7-88aeb88b0072> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/46caa7db-e0b7-44c8-9961-d578be0cc2d2> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/555ee8ce-5c85-4317-acba-70243c567682> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/59b4887c-8d59-403e-9985-69bb7d72e0ef> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/63b2ca4c-8412-4fe5-b91e-d8215ce9e4f5> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/676988b9-6d9f-4171-8f3a-4945b1617e65> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/76277c10-74c9-4340-8437-6afbf5454dbc> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/7b573a5b-d669-4596-8711-1cdd0c2075a4> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/7de06515-7331-437b-a9bd-75c2722722d1> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/8df2e6d3-2db7-402d-97f5-d107b30cbd73> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/96be4cd7-5372-4658-bec2-aa3bfa2cd716> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/98d5377a-4ca9-4223-bed3-8e2fc6e5a593> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/9a28f7f8-1614-4a92-9ca3-e72d7c35aae2> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/b1bfe3ef-8057-42b1-9cba-f778448457dc> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/b229613e-9f87-4183-97db-60e405692f38> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/d724daa8-5a6b-45ce-8f05-f35d134ae4e1> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/dc38ed77-8aa2-499b-acf4-86c52ffdc7b0> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/e910cf6a-64f4-4ef5-bab5-667315b04029> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/ee6914ff-e911-42ba-b1b2-35a56bcf5872> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/f3d5d5d7-c64f-43a4-9a20-5b7a5277a3d3> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/82236dd4-56c3-48ac-a0d7-667119959d56> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/12c6a838-78de-40d1-b3b8-0c554c5eb3a4> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/44fce966-42ee-4e7c-8d62-7403984ce433> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/30d80684-5d48-4bfa-b6ef-10d745ab1131> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/4ac1910c-dd05-496d-bb48-8797247849f8> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/ffd1d721-28f5-4660-b5fe-600b1425ae61> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/b93d393c-542d-48f8-9e68-4386f4c097d5> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/284aeb48-20e2-4017-835e-a8f52273760d> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/c267227f-f436-490a-8514-b856b1613bf7> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/cac78e8c-96f8-48d6-8517-e2d1247cb7c6> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/e0b0d1f4-3aca-4b1e-ad77-0ee92bbcafac> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/d286c450-c25f-4214-93b3-33ee714584ff> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/4fc67384-1740-4f8c-a14b-47062336cfc8> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/0bb48f75-9245-4605-a875-a63677f5b2b2> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/74146ed1-d4dc-403a-b4ac-f1c62fcf9b31> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/597e5f25-6520-4a5f-99ee-eadf3fa08c88> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/557891be-3329-4d13-afd9-b87dac82b127> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/b60cadee-2764-4532-8604-039dc3cbc8c6> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/ffbd917b-baa3-47cc-8995-230a48bed7f4> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/fb19e60b-2779-430a-875c-3b2933820181> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/0a802a9f-9d34-4901-898f-bd2af75897ef> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/988072ca-4e15-4d9b-bb28-2a20a36523b7> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/dad5339c-6d34-4d74-8bd5-3db5039061e8> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/a0145fd3-a806-46e1-8ac0-3b5caad0e156> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/8963371c-b4e3-494e-abe1-f786c71e3adf> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/4b847125-82b5-459f-ace9-80956618cf3a> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/4e39d98b-0bf9-477c-bc5b-420a87528993> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/b6b1cd19-0d1c-4f55-a13f-e348abf7b61e> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/2e1762af-2bf8-4584-bf8d-e8458fa86b39> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/dac4d875-c85e-4898-9c94-2b1e943e9200> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/dc76a384-5b51-4123-be0b-be3cc7da5ff9> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/381c9fad-4835-427e-80ae-1418974f73fb> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/49f3b95c-41bb-4945-a82d-330aedd18b62> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/f5f152c0-b877-428e-b6b9-3a0fae304bdd> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/a5d0e0a7-b0ac-4d37-a50d-ed82f8d4c172> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/0cd2c3e9-ee4f-4082-b3ca-66220eee94f0> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/ced19814-3b5c-41b0-bf99-7610a8d73005> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/0d3a88af-ff24-41c3-8149-43058b794dcd> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/ca144cd0-a22d-4e1b-afbf-2edb52e0077e> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/6e85808f-777f-42a6-b920-0a9cedf0c298> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/22c002bc-762a-492f-a38f-58352864a964> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/ca98fcf0-6c5f-40e7-a0e5-d96b29d0d141> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/e9e1f45a-86e2-4aa1-8204-065275957b7e> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
    }
  }
