
  DELETE DATA {
    GRAPH <http://mu.semte.ch/graphs/organizations/b36da606fba6dd4dc99ae1ef5f4a52bba3268d33f4bc2cd1e65b87f01f35101a/LoketLB-LPDCGebruiker> {
      <http://data.lblod.info/id/public-service/a37fee6b-c454-4448-b0c2-2e917f396557> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
    }
  } INSERT DATA {
    GRAPH <http://mu.semte.ch/graphs/organizations/b36da606fba6dd4dc99ae1ef5f4a52bba3268d33f4bc2cd1e65b87f01f35101a/LoketLB-LPDCGebruiker> {
      <http://data.lblod.info/id/public-service/a37fee6b-c454-4448-b0c2-2e917f396557> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
    }
  }
