
  DELETE DATA {
    GRAPH <http://mu.semte.ch/graphs/organizations/99ed6eee81a7aca47517cbffb46eaba38f3987eeb4ad32c020898644769eb615/LoketLB-LPDCGebruiker> {
      <http://data.lblod.info/id/public-service/380ba80b-08d5-45cf-8056-7e1a23fe51ee> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/2c8d8926-6da9-4214-a24b-18f75a6c9edb> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/9f2f7465-b3ae-4899-b611-318945b36a68> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/44abebd3-0a4b-443c-b31b-57951b472f21> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/5d3f87b4-8428-4caa-87e4-572edb685daa> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/4b197e23-de73-4643-9633-36001de625f6> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/72955d64-fa60-4181-8c5f-69daa6e6f5b4> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/ef8e6bdc-10ab-4c1a-a04c-022bc29b25d6> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/c1f6c474-94a6-45f1-b9c7-0ad3c9811630> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/2962bfb0-fdc7-4042-a6ff-41306f5b917f> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/272edf0e-f2dd-4467-b76b-776b9bcc28c9> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/89b3cda3-1c75-4e6d-b586-12b6b39ba67b> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/b80fc7e3-371c-4c71-af76-53f2e9034432> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/e61bd29b-50fa-4ba9-96de-1aab56064d44> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/a20950c1-0378-47af-99df-2893277c07da> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/1eea2285-8ff7-4055-a3a4-2d6e5cafc634> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/e101696d-c2ac-4541-9246-b6b623d52265> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/5cddcca3-b47d-4316-b441-38eea61ddec8> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/7d4cec58-cd4a-4509-ad4a-e76175f9ac06> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/228dfdb8-6602-48bb-9ac9-ead5c097905d> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/894a41e8-9e68-4618-b59c-ff80b8b94045> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/c224000b-a1c7-4e35-abe2-25cdfe4ae5be> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/af96ba52-9feb-47d8-921a-d7604835c791> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/1b924adb-a02e-4f10-9e9a-9947d147816b> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/155a3c29-a53f-4814-b485-04f2ed2ba212> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/f6895580-16db-4db8-bd19-53219107556d> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/1cc3a17f-a67f-4638-bf9e-bb8a9f7692f5> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/ef5cf6ac-6103-48f5-968d-8c2f56dbd610> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/06a2478b-cad1-45a1-9544-d4d192639b2b> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/b5e978c7-10dd-4139-a6a4-603afdc0b546> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/e9f0325b-7e97-48a1-8782-9a3ec9871a21> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/c0412b27-679c-488a-928c-be97b180faa5> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/4b205ad4-b05c-4b43-9d4d-a4d2bdfca31a> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/7257cc7c-a6f7-4dd3-8e24-646af5c58693> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/065c3bee-9707-4f5c-ba19-eeb84efe1fa4> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/8767bbee-52ee-4bf2-a6af-bad40b859293> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/733018fb-6528-4f4a-b4bf-1361cec39148> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/39136807-e994-4cc9-8281-744f226d9281> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/faa04981-afa4-419e-bf9d-d248e90b46a4> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/ca689469-596c-4697-b717-0f5de258e4dd> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/550f005e-d7e4-438f-b1d7-0406fabf8f14> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/cd4f54cf-a90b-4fee-a80b-069c122f5fc7> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/29d8b4a7-fc6d-495d-9db3-a607b278ab7b> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/5ad0846f-b759-448c-86ee-f8bf6c08edce> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/9b144026-a707-4caf-8f7b-12f92d793061> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/805ea17d-9d9d-4c56-9c77-1725d320a4b7> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/e2076218-c20f-4400-bf1f-bc0a67c09d7d> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/0b92aa63-de64-41ac-8b07-ff1f04ce04ef> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/fe23cdec-b2f1-47b3-b568-3a7dc216423b> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/ddbaf60c-a2cb-4aa6-b336-ca46d585d95b> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/706cb877-5625-4745-823c-453bf80cdce1> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/a1f254bd-1d59-476d-a3e7-695c0b9342cb> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/e14c0e1b-bd6f-43dc-aa03-665adccad9d9> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/34b94eb6-5fa5-4e92-bd6a-3b7dbe866f81> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/15f45bd5-b5d2-4135-b598-1af9ea0cfa0c> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/34dfe417-918b-42b7-af1d-76b89e82cff5> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/a81f5d82-0b33-48bb-a320-5567e89d4729> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/b0fbcb6f-33ef-4638-85d0-bb8164dccfdb> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/446f9cb6-3acf-4425-be41-3c90fc2dc484> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/304b3ded-d90f-4b76-97d9-3bc912f5a5b8> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/4ae82f22-457e-48fb-93eb-3989fd24ae15> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/ce9f872b-b48f-46cb-831d-ade07fd72ba5> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/9c495eb2-a2e4-46bc-9380-29b1cc30f755> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/806d179d-c202-45ba-92cf-65f443270e25> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/540a5160-0dce-4837-8603-361ed33eb168> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/141108a1-9514-4f18-a4a2-547e240d7367> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/b83cc00d-2f5e-414a-b5df-a61f835022da> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/eb7d1abc-7fe1-4f80-82b8-d4c7325b1f9d> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/7ccf7999-5771-4760-a94d-83b8d4b9117d> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/8e4d31a8-7fff-4bfa-beb6-24fae52b960a> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/e052a443-c723-4f10-8110-259acfdb76b5> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/bf1efebd-2f32-47aa-a0dd-ccb6173546f0> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/bd9f9563-47a9-4a8f-b1e2-e9a0594e0889> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/0bf5df6d-4f15-478d-8906-6399f356adad> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/df2172d9-0656-4b7f-96a0-c0a3b9cd0cfd> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/c341061e-42d8-4623-968e-0c07486419c3> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/135d86fd-380c-43ed-8b51-3ec5df0c04e5> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/3c16eee8-46f6-4304-87c6-249256016281> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/990a1edc-bedf-4d95-b8eb-5bd6a43242f3> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/5fd65dfd-75ac-422c-a161-eb3f30e7bf39> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/0ee5906c-f070-427e-b795-968efe587828> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/5b3f9596-91a7-4b61-b6eb-51494a373f5a> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/7de0de94-e46d-47ba-aa57-29d2f7701d93> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/11bfb970-61eb-437c-a24f-b4b6e7d2dad3> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/52e63b56-9a4c-425c-a0c9-39313ea92df8> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/2f203889-de7e-4cfe-b830-2609f57d0887> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/47ca9a41-459a-4dbd-9897-55c8d6eb2048> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/c14cbb9a-d75c-4867-9f63-c5f0691016f2> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
    }
  } INSERT DATA {
    GRAPH <http://mu.semte.ch/graphs/organizations/99ed6eee81a7aca47517cbffb46eaba38f3987eeb4ad32c020898644769eb615/LoketLB-LPDCGebruiker> {
      <http://data.lblod.info/id/public-service/380ba80b-08d5-45cf-8056-7e1a23fe51ee> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/2c8d8926-6da9-4214-a24b-18f75a6c9edb> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/9f2f7465-b3ae-4899-b611-318945b36a68> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/44abebd3-0a4b-443c-b31b-57951b472f21> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/5d3f87b4-8428-4caa-87e4-572edb685daa> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/4b197e23-de73-4643-9633-36001de625f6> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/72955d64-fa60-4181-8c5f-69daa6e6f5b4> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/ef8e6bdc-10ab-4c1a-a04c-022bc29b25d6> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/c1f6c474-94a6-45f1-b9c7-0ad3c9811630> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/2962bfb0-fdc7-4042-a6ff-41306f5b917f> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/272edf0e-f2dd-4467-b76b-776b9bcc28c9> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/89b3cda3-1c75-4e6d-b586-12b6b39ba67b> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/b80fc7e3-371c-4c71-af76-53f2e9034432> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/e61bd29b-50fa-4ba9-96de-1aab56064d44> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/a20950c1-0378-47af-99df-2893277c07da> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/1eea2285-8ff7-4055-a3a4-2d6e5cafc634> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/e101696d-c2ac-4541-9246-b6b623d52265> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/5cddcca3-b47d-4316-b441-38eea61ddec8> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/7d4cec58-cd4a-4509-ad4a-e76175f9ac06> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/228dfdb8-6602-48bb-9ac9-ead5c097905d> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/894a41e8-9e68-4618-b59c-ff80b8b94045> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/c224000b-a1c7-4e35-abe2-25cdfe4ae5be> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/af96ba52-9feb-47d8-921a-d7604835c791> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/1b924adb-a02e-4f10-9e9a-9947d147816b> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/155a3c29-a53f-4814-b485-04f2ed2ba212> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/f6895580-16db-4db8-bd19-53219107556d> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/1cc3a17f-a67f-4638-bf9e-bb8a9f7692f5> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/ef5cf6ac-6103-48f5-968d-8c2f56dbd610> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/06a2478b-cad1-45a1-9544-d4d192639b2b> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/b5e978c7-10dd-4139-a6a4-603afdc0b546> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/e9f0325b-7e97-48a1-8782-9a3ec9871a21> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/c0412b27-679c-488a-928c-be97b180faa5> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/4b205ad4-b05c-4b43-9d4d-a4d2bdfca31a> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/7257cc7c-a6f7-4dd3-8e24-646af5c58693> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/065c3bee-9707-4f5c-ba19-eeb84efe1fa4> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/8767bbee-52ee-4bf2-a6af-bad40b859293> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/733018fb-6528-4f4a-b4bf-1361cec39148> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/39136807-e994-4cc9-8281-744f226d9281> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/faa04981-afa4-419e-bf9d-d248e90b46a4> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/ca689469-596c-4697-b717-0f5de258e4dd> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/550f005e-d7e4-438f-b1d7-0406fabf8f14> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/cd4f54cf-a90b-4fee-a80b-069c122f5fc7> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/29d8b4a7-fc6d-495d-9db3-a607b278ab7b> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/5ad0846f-b759-448c-86ee-f8bf6c08edce> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/9b144026-a707-4caf-8f7b-12f92d793061> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/805ea17d-9d9d-4c56-9c77-1725d320a4b7> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/e2076218-c20f-4400-bf1f-bc0a67c09d7d> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/0b92aa63-de64-41ac-8b07-ff1f04ce04ef> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/fe23cdec-b2f1-47b3-b568-3a7dc216423b> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/ddbaf60c-a2cb-4aa6-b336-ca46d585d95b> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/706cb877-5625-4745-823c-453bf80cdce1> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/a1f254bd-1d59-476d-a3e7-695c0b9342cb> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/e14c0e1b-bd6f-43dc-aa03-665adccad9d9> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/34b94eb6-5fa5-4e92-bd6a-3b7dbe866f81> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/15f45bd5-b5d2-4135-b598-1af9ea0cfa0c> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/34dfe417-918b-42b7-af1d-76b89e82cff5> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/a81f5d82-0b33-48bb-a320-5567e89d4729> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/b0fbcb6f-33ef-4638-85d0-bb8164dccfdb> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/446f9cb6-3acf-4425-be41-3c90fc2dc484> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/304b3ded-d90f-4b76-97d9-3bc912f5a5b8> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/4ae82f22-457e-48fb-93eb-3989fd24ae15> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/ce9f872b-b48f-46cb-831d-ade07fd72ba5> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/9c495eb2-a2e4-46bc-9380-29b1cc30f755> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/806d179d-c202-45ba-92cf-65f443270e25> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/540a5160-0dce-4837-8603-361ed33eb168> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/141108a1-9514-4f18-a4a2-547e240d7367> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/b83cc00d-2f5e-414a-b5df-a61f835022da> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/eb7d1abc-7fe1-4f80-82b8-d4c7325b1f9d> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/7ccf7999-5771-4760-a94d-83b8d4b9117d> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/8e4d31a8-7fff-4bfa-beb6-24fae52b960a> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/e052a443-c723-4f10-8110-259acfdb76b5> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/bf1efebd-2f32-47aa-a0dd-ccb6173546f0> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/bd9f9563-47a9-4a8f-b1e2-e9a0594e0889> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/0bf5df6d-4f15-478d-8906-6399f356adad> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/df2172d9-0656-4b7f-96a0-c0a3b9cd0cfd> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/c341061e-42d8-4623-968e-0c07486419c3> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/135d86fd-380c-43ed-8b51-3ec5df0c04e5> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/3c16eee8-46f6-4304-87c6-249256016281> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/990a1edc-bedf-4d95-b8eb-5bd6a43242f3> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/5fd65dfd-75ac-422c-a161-eb3f30e7bf39> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/0ee5906c-f070-427e-b795-968efe587828> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/5b3f9596-91a7-4b61-b6eb-51494a373f5a> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/7de0de94-e46d-47ba-aa57-29d2f7701d93> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/11bfb970-61eb-437c-a24f-b4b6e7d2dad3> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/52e63b56-9a4c-425c-a0c9-39313ea92df8> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/2f203889-de7e-4cfe-b830-2609f57d0887> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/47ca9a41-459a-4dbd-9897-55c8d6eb2048> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
<http://data.lblod.info/id/public-service/c14cbb9a-d75c-4867-9f63-c5f0691016f2> <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#forMunicipalityMerger> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
    }
  }
