PREFIX organisatie: <http://lblod.data.gift/vocabularies/organisatie/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {
  ?s skos:topConceptOf <http://data.vlaanderen.be/id/conceptscheme/BestuurseenheidClassificatieCode> .
} WHERE {
  ?s a organisatie:BestuurseenheidClassificatieCode .
}
