PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX organisatie: <http://lblod.data.gift/vocabularies/organisatie/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {
  ?s a ext:BestuurseenheidClassificatieCode, skos:Concept.
} WHERE {
  ?s a organisatie:BestuurseenheidClassificatieCode .
}
