PREFIX cpsv:    <http://purl.org/vocab/cpsv#>
PREFIX adms:    <http://www.w3.org/ns/adms#>
PREFIX ext:     <http://mu.semte.ch/vocabularies/ext/>
INSERT {
    GRAPH <?bestuurseenheidGraph> {
        ?instantie ext:reviewStatus <http://lblod.data.gift/concepts/cf22e8d1-23c3-45da-89bc-00826eaf23c3>.
    }
}
WHERE {
    GRAPH ?bestuurseenheidGraph {
        ?instantie a cpsv:PublicService .
        ?instantie dcterms:source ?concept.
    }
    GRAPH <http://mu.semte.ch/graphs/public> {
        ?concept adms:status ?conceptStatus.
    }
}