# Remove all resources related to the nuts codelist from the public graph. These
# will be replace by the updated codelist in a following migration.
DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s ?p ?o.
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s ?p ?o.
    FILTER (STRSTARTS(STR(?s), ?prefix))
  }
  VALUES ?prefix {
    "http://data.europa.eu/nuts/scheme/"
    "http://data.europa.eu/nuts/code/"
  }
}
